//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/identity_providers_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityProviders_Create_FullMethodName = "/osac.private.v1.IdentityProviders/Create"
	IdentityProviders_List_FullMethodName   = "/osac.private.v1.IdentityProviders/List"
	IdentityProviders_Get_FullMethodName    = "/osac.private.v1.IdentityProviders/Get"
	IdentityProviders_Update_FullMethodName = "/osac.private.v1.IdentityProviders/Update"
	IdentityProviders_Delete_FullMethodName = "/osac.private.v1.IdentityProviders/Delete"
	IdentityProviders_Signal_FullMethodName = "/osac.private.v1.IdentityProviders/Signal"
)

// IdentityProvidersClient is the client API for IdentityProviders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityProviders service provides internal operations for managing identity providers.
type IdentityProvidersClient interface {
	// Creates a new identity provider.
	Create(ctx context.Context, in *IdentityProvidersCreateRequest, opts ...grpc.CallOption) (*IdentityProvidersCreateResponse, error)
	// Lists all identity providers.
	// Use filter with metadata.tenant to scope to a specific tenant.
	List(ctx context.Context, in *IdentityProvidersListRequest, opts ...grpc.CallOption) (*IdentityProvidersListResponse, error)
	// Retrieves an identity provider by name.
	Get(ctx context.Context, in *IdentityProvidersGetRequest, opts ...grpc.CallOption) (*IdentityProvidersGetResponse, error)
	// Updates an existing identity provider.
	Update(ctx context.Context, in *IdentityProvidersUpdateRequest, opts ...grpc.CallOption) (*IdentityProvidersUpdateResponse, error)
	// Deletes an identity provider.
	Delete(ctx context.Context, in *IdentityProvidersDeleteRequest, opts ...grpc.CallOption) (*IdentityProvidersDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *IdentityProvidersSignalRequest, opts ...grpc.CallOption) (*IdentityProvidersSignalResponse, error)
}

type identityProvidersClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityProvidersClient(cc grpc.ClientConnInterface) IdentityProvidersClient {
	return &identityProvidersClient{cc}
}

func (c *identityProvidersClient) Create(ctx context.Context, in *IdentityProvidersCreateRequest, opts ...grpc.CallOption) (*IdentityProvidersCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersCreateResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProvidersClient) List(ctx context.Context, in *IdentityProvidersListRequest, opts ...grpc.CallOption) (*IdentityProvidersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersListResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProvidersClient) Get(ctx context.Context, in *IdentityProvidersGetRequest, opts ...grpc.CallOption) (*IdentityProvidersGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersGetResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProvidersClient) Update(ctx context.Context, in *IdentityProvidersUpdateRequest, opts ...grpc.CallOption) (*IdentityProvidersUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersUpdateResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProvidersClient) Delete(ctx context.Context, in *IdentityProvidersDeleteRequest, opts ...grpc.CallOption) (*IdentityProvidersDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersDeleteResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProvidersClient) Signal(ctx context.Context, in *IdentityProvidersSignalRequest, opts ...grpc.CallOption) (*IdentityProvidersSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvidersSignalResponse)
	err := c.cc.Invoke(ctx, IdentityProviders_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityProvidersServer is the server API for IdentityProviders service.
// All implementations must embed UnimplementedIdentityProvidersServer
// for forward compatibility.
//
// IdentityProviders service provides internal operations for managing identity providers.
type IdentityProvidersServer interface {
	// Creates a new identity provider.
	Create(context.Context, *IdentityProvidersCreateRequest) (*IdentityProvidersCreateResponse, error)
	// Lists all identity providers.
	// Use filter with metadata.tenant to scope to a specific tenant.
	List(context.Context, *IdentityProvidersListRequest) (*IdentityProvidersListResponse, error)
	// Retrieves an identity provider by name.
	Get(context.Context, *IdentityProvidersGetRequest) (*IdentityProvidersGetResponse, error)
	// Updates an existing identity provider.
	Update(context.Context, *IdentityProvidersUpdateRequest) (*IdentityProvidersUpdateResponse, error)
	// Deletes an identity provider.
	Delete(context.Context, *IdentityProvidersDeleteRequest) (*IdentityProvidersDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *IdentityProvidersSignalRequest) (*IdentityProvidersSignalResponse, error)
	mustEmbedUnimplementedIdentityProvidersServer()
}

// UnimplementedIdentityProvidersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityProvidersServer struct{}

func (UnimplementedIdentityProvidersServer) Create(context.Context, *IdentityProvidersCreateRequest) (*IdentityProvidersCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedIdentityProvidersServer) List(context.Context, *IdentityProvidersListRequest) (*IdentityProvidersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedIdentityProvidersServer) Get(context.Context, *IdentityProvidersGetRequest) (*IdentityProvidersGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedIdentityProvidersServer) Update(context.Context, *IdentityProvidersUpdateRequest) (*IdentityProvidersUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedIdentityProvidersServer) Delete(context.Context, *IdentityProvidersDeleteRequest) (*IdentityProvidersDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedIdentityProvidersServer) Signal(context.Context, *IdentityProvidersSignalRequest) (*IdentityProvidersSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedIdentityProvidersServer) mustEmbedUnimplementedIdentityProvidersServer() {}
func (UnimplementedIdentityProvidersServer) testEmbeddedByValue()                           {}

// UnsafeIdentityProvidersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityProvidersServer will
// result in compilation errors.
type UnsafeIdentityProvidersServer interface {
	mustEmbedUnimplementedIdentityProvidersServer()
}

func RegisterIdentityProvidersServer(s grpc.ServiceRegistrar, srv IdentityProvidersServer) {
	// If the following call pancis, it indicates UnimplementedIdentityProvidersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityProviders_ServiceDesc, srv)
}

func _IdentityProviders_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).Create(ctx, req.(*IdentityProvidersCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviders_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).List(ctx, req.(*IdentityProvidersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviders_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).Get(ctx, req.(*IdentityProvidersGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviders_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).Update(ctx, req.(*IdentityProvidersUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviders_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).Delete(ctx, req.(*IdentityProvidersDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviders_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProvidersSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProvidersServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviders_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProvidersServer).Signal(ctx, req.(*IdentityProvidersSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityProviders_ServiceDesc is the grpc.ServiceDesc for IdentityProviders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityProviders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.IdentityProviders",
	HandlerType: (*IdentityProvidersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _IdentityProviders_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _IdentityProviders_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _IdentityProviders_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _IdentityProviders_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IdentityProviders_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _IdentityProviders_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/identity_providers_service.proto",
}
