//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/network_class_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for NetworkClass resources.
type NetworkClassState int32

const (
	// State is unknown or has not been determined yet.
	NetworkClassState_NETWORK_CLASS_STATE_UNSPECIFIED NetworkClassState = 0
	// The network class is being initialized and is not yet ready for use.
	NetworkClassState_NETWORK_CLASS_STATE_PENDING NetworkClassState = 1
	// The network class is fully operational and available for creating VirtualNetworks.
	NetworkClassState_NETWORK_CLASS_STATE_READY NetworkClassState = 2
	// The network class has encountered an error and cannot be used for creating VirtualNetworks.
	NetworkClassState_NETWORK_CLASS_STATE_FAILED NetworkClassState = 3
)

// Enum value maps for NetworkClassState.
var (
	NetworkClassState_name = map[int32]string{
		0: "NETWORK_CLASS_STATE_UNSPECIFIED",
		1: "NETWORK_CLASS_STATE_PENDING",
		2: "NETWORK_CLASS_STATE_READY",
		3: "NETWORK_CLASS_STATE_FAILED",
	}
	NetworkClassState_value = map[string]int32{
		"NETWORK_CLASS_STATE_UNSPECIFIED": 0,
		"NETWORK_CLASS_STATE_PENDING":     1,
		"NETWORK_CLASS_STATE_READY":       2,
		"NETWORK_CLASS_STATE_FAILED":      3,
	}
)

func (x NetworkClassState) Enum() *NetworkClassState {
	p := new(NetworkClassState)
	*p = x
	return p
}

func (x NetworkClassState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkClassState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_network_class_type_proto_enumTypes[0].Descriptor()
}

func (NetworkClassState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_network_class_type_proto_enumTypes[0]
}

func (x NetworkClassState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Describes a network implementation strategy available for creating virtual networks.
//
// NetworkClass represents a specific network backend implementation that VirtualNetworks can use. For example,
// there could be a network class `udn-net` to describe networks implemented using User-Defined Networks in
// Kubernetes, and another `phys-net` for networks backed by physical network infrastructure.
//
// This is similar to the _storage class_ concept used by Kubernetes for persistent volumes, or the _instance type_
// concept used by cloud providers for compute resources.
//
// Users query available NetworkClasses to discover which network implementation strategies they can choose when
// creating VirtualNetworks. The `implementation_strategy` field is the key identifier that VirtualNetwork resources
// reference to select their network backend.
type NetworkClass struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the network class.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the network class.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Human friendly short description of the network class, only a few words, suitable for displaying in one single
	// line on a UI or CLI. For example: "UDN Network" or "Physical Network".
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Human friendly long description of the network class, using Markdown format. This should explain the
	// characteristics of networks created using this class, including performance characteristics, isolation
	// guarantees, and any limitations or requirements.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Implementation strategy identifier for this network class. This is the discriminator that VirtualNetwork
	// resources use to select which network backend to use. For example: "udn-net", "phys-net", "ovn-kubernetes".
	//
	// This value is system-defined and immutable once the NetworkClass is created.
	ImplementationStrategy string `protobuf:"bytes,5,opt,name=implementation_strategy,json=implementationStrategy,proto3" json:"implementation_strategy,omitempty"`
	// Class-specific configuration constraints and options. These define implementation-specific parameters that
	// networks using this class must or may configure.
	Constraints *NetworkClassConstraints `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// Capabilities that this network class supports. These describe what features are available when using this
	// network implementation strategy.
	Capabilities *NetworkClassCapabilities `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Current operational status of the network class.
	Status *NetworkClassStatus `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// Whether this NetworkClass is the default. Only one NetworkClass can be the default at a time.
	// When a VirtualNetwork is created without specifying network_class, the default NetworkClass is used.
	IsDefault *bool `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	// Identifier of the fabric manager that handles physical network operations for this class. The fabric manager
	// controls all fabric-level operations: virtual network segments, security groups, external IPs, and NAT gateways.
	// For example: "netris", "neutron".
	FabricManager string `protobuf:"bytes,10,opt,name=fabric_manager,json=fabricManager,proto3" json:"fabric_manager,omitempty"`
	// Identifier of the K8s manager that bridges the Kubernetes overlay to the physical fabric. Only needed for regions
	// that host VMs — the K8s manager creates the overlay network on hosting clusters and bridges it to the fabric
	// segment. For example: "cudn_localnet". If not set, the region does not support VM workloads.
	K8SManager *string `protobuf:"bytes,11,opt,name=k8s_manager,json=k8sManager,proto3,oneof" json:"k8s_manager,omitempty"`
	// Desired configuration for this network class.
	Spec          *NetworkClassSpec `protobuf:"bytes,12,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClass) Reset() {
	*x = NetworkClass{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClass) ProtoMessage() {}

func (x *NetworkClass) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkClass) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NetworkClass) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NetworkClass) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NetworkClass) GetImplementationStrategy() string {
	if x != nil {
		return x.ImplementationStrategy
	}
	return ""
}

func (x *NetworkClass) GetConstraints() *NetworkClassConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *NetworkClass) GetCapabilities() *NetworkClassCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NetworkClass) GetStatus() *NetworkClassStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NetworkClass) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *NetworkClass) GetFabricManager() string {
	if x != nil {
		return x.FabricManager
	}
	return ""
}

func (x *NetworkClass) GetK8SManager() string {
	if x != nil && x.K8SManager != nil {
		return *x.K8SManager
	}
	return ""
}

func (x *NetworkClass) GetSpec() *NetworkClassSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *NetworkClass) SetId(v string) {
	x.Id = v
}

func (x *NetworkClass) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *NetworkClass) SetTitle(v string) {
	x.Title = v
}

func (x *NetworkClass) SetDescription(v string) {
	x.Description = v
}

func (x *NetworkClass) SetImplementationStrategy(v string) {
	x.ImplementationStrategy = v
}

func (x *NetworkClass) SetConstraints(v *NetworkClassConstraints) {
	x.Constraints = v
}

func (x *NetworkClass) SetCapabilities(v *NetworkClassCapabilities) {
	x.Capabilities = v
}

func (x *NetworkClass) SetStatus(v *NetworkClassStatus) {
	x.Status = v
}

func (x *NetworkClass) SetIsDefault(v bool) {
	x.IsDefault = &v
}

func (x *NetworkClass) SetFabricManager(v string) {
	x.FabricManager = v
}

func (x *NetworkClass) SetK8SManager(v string) {
	x.K8SManager = &v
}

func (x *NetworkClass) SetSpec(v *NetworkClassSpec) {
	x.Spec = v
}

func (x *NetworkClass) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *NetworkClass) HasConstraints() bool {
	if x == nil {
		return false
	}
	return x.Constraints != nil
}

func (x *NetworkClass) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.Capabilities != nil
}

func (x *NetworkClass) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *NetworkClass) HasIsDefault() bool {
	if x == nil {
		return false
	}
	return x.IsDefault != nil
}

func (x *NetworkClass) HasK8SManager() bool {
	if x == nil {
		return false
	}
	return x.K8SManager != nil
}

func (x *NetworkClass) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *NetworkClass) ClearMetadata() {
	x.Metadata = nil
}

func (x *NetworkClass) ClearConstraints() {
	x.Constraints = nil
}

func (x *NetworkClass) ClearCapabilities() {
	x.Capabilities = nil
}

func (x *NetworkClass) ClearStatus() {
	x.Status = nil
}

func (x *NetworkClass) ClearIsDefault() {
	x.IsDefault = nil
}

func (x *NetworkClass) ClearK8SManager() {
	x.K8SManager = nil
}

func (x *NetworkClass) ClearSpec() {
	x.Spec = nil
}

type NetworkClass_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the network class.
	Id string
	// Metadata of the network class.
	Metadata *Metadata
	// Human friendly short description of the network class, only a few words, suitable for displaying in one single
	// line on a UI or CLI. For example: "UDN Network" or "Physical Network".
	Title string
	// Human friendly long description of the network class, using Markdown format. This should explain the
	// characteristics of networks created using this class, including performance characteristics, isolation
	// guarantees, and any limitations or requirements.
	Description string
	// Implementation strategy identifier for this network class. This is the discriminator that VirtualNetwork
	// resources use to select which network backend to use. For example: "udn-net", "phys-net", "ovn-kubernetes".
	//
	// This value is system-defined and immutable once the NetworkClass is created.
	ImplementationStrategy string
	// Class-specific configuration constraints and options. These define implementation-specific parameters that
	// networks using this class must or may configure.
	Constraints *NetworkClassConstraints
	// Capabilities that this network class supports. These describe what features are available when using this
	// network implementation strategy.
	Capabilities *NetworkClassCapabilities
	// Current operational status of the network class.
	Status *NetworkClassStatus
	// Whether this NetworkClass is the default. Only one NetworkClass can be the default at a time.
	// When a VirtualNetwork is created without specifying network_class, the default NetworkClass is used.
	IsDefault *bool
	// Identifier of the fabric manager that handles physical network operations for this class. The fabric manager
	// controls all fabric-level operations: virtual network segments, security groups, external IPs, and NAT gateways.
	// For example: "netris", "neutron".
	FabricManager string
	// Identifier of the K8s manager that bridges the Kubernetes overlay to the physical fabric. Only needed for regions
	// that host VMs — the K8s manager creates the overlay network on hosting clusters and bridges it to the fabric
	// segment. For example: "cudn_localnet". If not set, the region does not support VM workloads.
	K8SManager *string
	// Desired configuration for this network class.
	Spec *NetworkClassSpec
}

func (b0 NetworkClass_builder) Build() *NetworkClass {
	m0 := &NetworkClass{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Title = b.Title
	x.Description = b.Description
	x.ImplementationStrategy = b.ImplementationStrategy
	x.Constraints = b.Constraints
	x.Capabilities = b.Capabilities
	x.Status = b.Status
	x.IsDefault = b.IsDefault
	x.FabricManager = b.FabricManager
	x.K8SManager = b.K8SManager
	x.Spec = b.Spec
	return m0
}

// Desired configuration for a NetworkClass.
type NetworkClassSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Default networking configuration for tenant onboarding. When a tenant is created, the system uses these
	// defaults to auto-create a VirtualNetwork, Subnet, and SecurityGroup for the tenant.
	Defaults      *NetworkDefaults `protobuf:"bytes,1,opt,name=defaults,proto3" json:"defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassSpec) Reset() {
	*x = NetworkClassSpec{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassSpec) ProtoMessage() {}

func (x *NetworkClassSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassSpec) GetDefaults() *NetworkDefaults {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *NetworkClassSpec) SetDefaults(v *NetworkDefaults) {
	x.Defaults = v
}

func (x *NetworkClassSpec) HasDefaults() bool {
	if x == nil {
		return false
	}
	return x.Defaults != nil
}

func (x *NetworkClassSpec) ClearDefaults() {
	x.Defaults = nil
}

type NetworkClassSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Default networking configuration for tenant onboarding. When a tenant is created, the system uses these
	// defaults to auto-create a VirtualNetwork, Subnet, and SecurityGroup for the tenant.
	Defaults *NetworkDefaults
}

func (b0 NetworkClassSpec_builder) Build() *NetworkClassSpec {
	m0 := &NetworkClassSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Defaults = b.Defaults
	return m0
}

// Default networking configuration used during tenant onboarding.
//
// When a tenant is created, the system reads these defaults from the NetworkClass and auto-creates
// a default VirtualNetwork (using virtual_network_cidr), Subnet (using subnet_cidr), and SecurityGroup
// (using ingress_rules and egress_rules) for the tenant. All fields are optional — defaults can be
// partially populated (e.g., CIDRs only without security rules).
type NetworkDefaults struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Default CIDR for auto-created tenant VirtualNetwork. Must be valid IPv4 CIDR notation.
	// Example: "10.0.0.0/16"
	VirtualNetworkCidr string `protobuf:"bytes,1,opt,name=virtual_network_cidr,json=virtualNetworkCidr,proto3" json:"virtual_network_cidr,omitempty"`
	// Default CIDR for auto-created tenant Subnet. Must be valid IPv4 CIDR notation and fall within the
	// virtual_network_cidr range.
	// Example: "10.0.1.0/24"
	SubnetCidr string `protobuf:"bytes,2,opt,name=subnet_cidr,json=subnetCidr,proto3" json:"subnet_cidr,omitempty"`
	// Default ingress rules for auto-created tenant SecurityGroup.
	IngressRules []*SecurityRule `protobuf:"bytes,3,rep,name=ingress_rules,json=ingressRules,proto3" json:"ingress_rules,omitempty"`
	// Default egress rules for auto-created tenant SecurityGroup.
	EgressRules   []*SecurityRule `protobuf:"bytes,4,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDefaults) Reset() {
	*x = NetworkDefaults{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDefaults) ProtoMessage() {}

func (x *NetworkDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkDefaults) GetVirtualNetworkCidr() string {
	if x != nil {
		return x.VirtualNetworkCidr
	}
	return ""
}

func (x *NetworkDefaults) GetSubnetCidr() string {
	if x != nil {
		return x.SubnetCidr
	}
	return ""
}

func (x *NetworkDefaults) GetIngressRules() []*SecurityRule {
	if x != nil {
		return x.IngressRules
	}
	return nil
}

func (x *NetworkDefaults) GetEgressRules() []*SecurityRule {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

func (x *NetworkDefaults) SetVirtualNetworkCidr(v string) {
	x.VirtualNetworkCidr = v
}

func (x *NetworkDefaults) SetSubnetCidr(v string) {
	x.SubnetCidr = v
}

func (x *NetworkDefaults) SetIngressRules(v []*SecurityRule) {
	x.IngressRules = v
}

func (x *NetworkDefaults) SetEgressRules(v []*SecurityRule) {
	x.EgressRules = v
}

type NetworkDefaults_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Default CIDR for auto-created tenant VirtualNetwork. Must be valid IPv4 CIDR notation.
	// Example: "10.0.0.0/16"
	VirtualNetworkCidr string
	// Default CIDR for auto-created tenant Subnet. Must be valid IPv4 CIDR notation and fall within the
	// virtual_network_cidr range.
	// Example: "10.0.1.0/24"
	SubnetCidr string
	// Default ingress rules for auto-created tenant SecurityGroup.
	IngressRules []*SecurityRule
	// Default egress rules for auto-created tenant SecurityGroup.
	EgressRules []*SecurityRule
}

func (b0 NetworkDefaults_builder) Build() *NetworkDefaults {
	m0 := &NetworkDefaults{}
	b, x := &b0, m0
	_, _ = b, x
	x.VirtualNetworkCidr = b.VirtualNetworkCidr
	x.SubnetCidr = b.SubnetCidr
	x.IngressRules = b.IngressRules
	x.EgressRules = b.EgressRules
	return m0
}

// Defines configuration constraints for a specific NetworkClass implementation.
//
// This message contains implementation-specific parameters that may be required or optional when creating
// VirtualNetworks using this class. Currently minimal to allow for future extension.
type NetworkClassConstraints struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassConstraints) Reset() {
	*x = NetworkClassConstraints{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassConstraints) ProtoMessage() {}

func (x *NetworkClassConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type NetworkClassConstraints_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 NetworkClassConstraints_builder) Build() *NetworkClassConstraints {
	m0 := &NetworkClassConstraints{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Describes the capabilities supported by a NetworkClass.
//
// These fields indicate what network features are available when using this class for VirtualNetwork creation.
type NetworkClassCapabilities struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Whether this network class supports IPv4 addressing.
	SupportsIpv4 bool `protobuf:"varint,1,opt,name=supports_ipv4,json=supportsIpv4,proto3" json:"supports_ipv4,omitempty"`
	// Whether this network class supports IPv6 addressing.
	SupportsIpv6 bool `protobuf:"varint,2,opt,name=supports_ipv6,json=supportsIpv6,proto3" json:"supports_ipv6,omitempty"`
	// Whether this network class supports dual-stack (IPv4 + IPv6) configuration.
	SupportsDualStack bool `protobuf:"varint,3,opt,name=supports_dual_stack,json=supportsDualStack,proto3" json:"supports_dual_stack,omitempty"`
	// Whether this network class supports DPU (Data Processing Unit) offloading.
	DpuSupport    bool `protobuf:"varint,4,opt,name=dpu_support,json=dpuSupport,proto3" json:"dpu_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassCapabilities) Reset() {
	*x = NetworkClassCapabilities{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassCapabilities) ProtoMessage() {}

func (x *NetworkClassCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassCapabilities) GetSupportsIpv4() bool {
	if x != nil {
		return x.SupportsIpv4
	}
	return false
}

func (x *NetworkClassCapabilities) GetSupportsIpv6() bool {
	if x != nil {
		return x.SupportsIpv6
	}
	return false
}

func (x *NetworkClassCapabilities) GetSupportsDualStack() bool {
	if x != nil {
		return x.SupportsDualStack
	}
	return false
}

func (x *NetworkClassCapabilities) GetDpuSupport() bool {
	if x != nil {
		return x.DpuSupport
	}
	return false
}

func (x *NetworkClassCapabilities) SetSupportsIpv4(v bool) {
	x.SupportsIpv4 = v
}

func (x *NetworkClassCapabilities) SetSupportsIpv6(v bool) {
	x.SupportsIpv6 = v
}

func (x *NetworkClassCapabilities) SetSupportsDualStack(v bool) {
	x.SupportsDualStack = v
}

func (x *NetworkClassCapabilities) SetDpuSupport(v bool) {
	x.DpuSupport = v
}

type NetworkClassCapabilities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether this network class supports IPv4 addressing.
	SupportsIpv4 bool
	// Whether this network class supports IPv6 addressing.
	SupportsIpv6 bool
	// Whether this network class supports dual-stack (IPv4 + IPv6) configuration.
	SupportsDualStack bool
	// Whether this network class supports DPU (Data Processing Unit) offloading.
	DpuSupport bool
}

func (b0 NetworkClassCapabilities_builder) Build() *NetworkClassCapabilities {
	m0 := &NetworkClassCapabilities{}
	b, x := &b0, m0
	_, _ = b, x
	x.SupportsIpv4 = b.SupportsIpv4
	x.SupportsIpv6 = b.SupportsIpv6
	x.SupportsDualStack = b.SupportsDualStack
	x.DpuSupport = b.DpuSupport
	return m0
}

// Represents the current operational state of a NetworkClass.
type NetworkClassStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the network class.
	State NetworkClassState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.NetworkClassState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Identifier of the hub that was selected for this network class.
	// This is system-managed and used by the controller to track which hub cluster manages this class's resources.
	Hub           string `protobuf:"bytes,3,opt,name=hub,proto3" json:"hub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassStatus) Reset() {
	*x = NetworkClassStatus{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassStatus) ProtoMessage() {}

func (x *NetworkClassStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassStatus) GetState() NetworkClassState {
	if x != nil {
		return x.State
	}
	return NetworkClassState_NETWORK_CLASS_STATE_UNSPECIFIED
}

func (x *NetworkClassStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *NetworkClassStatus) GetHub() string {
	if x != nil {
		return x.Hub
	}
	return ""
}

func (x *NetworkClassStatus) SetState(v NetworkClassState) {
	x.State = v
}

func (x *NetworkClassStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *NetworkClassStatus) SetHub(v string) {
	x.Hub = v
}

func (x *NetworkClassStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *NetworkClassStatus) ClearMessage() {
	x.Message = nil
}

type NetworkClassStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the network class.
	State NetworkClassState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message *string
	// Identifier of the hub that was selected for this network class.
	// This is system-managed and used by the controller to track which hub cluster manages this class's resources.
	Hub string
}

func (b0 NetworkClassStatus_builder) Build() *NetworkClassStatus {
	m0 := &NetworkClassStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	x.Hub = b.Hub
	return m0
}

var File_osac_private_v1_network_class_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_network_class_type_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x6f,
	0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x04, 0x0a, 0x0c, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x17, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x12, 0x4a, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x4d, 0x0a,
	0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0c,
	0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a,
	0x0e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0b, 0x6b, 0x38, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x6b, 0x38, 0x73,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x04, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6b, 0x38, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x22, 0x50, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0xf9, 0x04, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x12, 0xa9, 0x01, 0x0a, 0x14, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x77, 0xba, 0x48, 0x74, 0xba, 0x01, 0x71, 0x0a, 0x0f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x12, 0x36,
	0x6d, 0x75, 0x73, 0x74, 0x20, 0x62, 0x65, 0x20, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x20, 0x49, 0x50,
	0x76, 0x34, 0x20, 0x43, 0x49, 0x44, 0x52, 0x20, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x20, 0x28, 0x65, 0x2e, 0x67, 0x2e, 0x2c, 0x20, 0x27, 0x31, 0x30, 0x2e, 0x30, 0x2e, 0x30, 0x2e,
	0x30, 0x2f, 0x31, 0x36, 0x27, 0x29, 0x1a, 0x26, 0x74, 0x68, 0x69, 0x73, 0x20, 0x3d, 0x3d, 0x20,
	0x27, 0x27, 0x20, 0x7c, 0x7c, 0x20, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x69, 0x73, 0x49, 0x70, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x28, 0x34, 0x2c, 0x20, 0x74, 0x72, 0x75, 0x65, 0x29, 0x52, 0x12,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x69,
	0x64, 0x72, 0x12, 0x98, 0x01, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x63, 0x69,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x77, 0xba, 0x48, 0x74, 0xba, 0x01, 0x71,
	0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64,
	0x72, 0x12, 0x36, 0x6d, 0x75, 0x73, 0x74, 0x20, 0x62, 0x65, 0x20, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x20, 0x49, 0x50, 0x76, 0x34, 0x20, 0x43, 0x49, 0x44, 0x52, 0x20, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x20, 0x28, 0x65, 0x2e, 0x67, 0x2e, 0x2c, 0x20, 0x27, 0x31, 0x30, 0x2e, 0x30,
	0x2e, 0x31, 0x2e, 0x30, 0x2f, 0x32, 0x34, 0x27, 0x29, 0x1a, 0x26, 0x74, 0x68, 0x69, 0x73, 0x20,
	0x3d, 0x3d, 0x20, 0x27, 0x27, 0x20, 0x7c, 0x7c, 0x20, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x69, 0x73,
	0x49, 0x70, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x28, 0x34, 0x2c, 0x20, 0x74, 0x72, 0x75, 0x65,
	0x29, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x43, 0x69, 0x64, 0x72, 0x12, 0x42, 0x0a,
	0x0d, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x0c, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x40, 0x0a, 0x0c, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0b, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x3a, 0x98, 0x01, 0xba, 0x48, 0x94, 0x01, 0x1a, 0x91, 0x01, 0x0a, 0x1f, 0x73,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x33,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x20, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x73, 0x20, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x20, 0x74, 0x6f, 0x20, 0x62, 0x65, 0x20,
	0x73, 0x65, 0x74, 0x1a, 0x39, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x5f, 0x63, 0x69, 0x64, 0x72, 0x20, 0x3d, 0x3d, 0x20, 0x27, 0x27, 0x20, 0x7c, 0x7c, 0x20, 0x74,
	0x68, 0x69, 0x73, 0x2e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x20, 0x21, 0x3d, 0x20, 0x27, 0x27, 0x22, 0x19,
	0x0a, 0x17, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x18, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x49, 0x70, 0x76, 0x34, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x49, 0x70, 0x76, 0x36,
	0x12, 0x2e, 0x0a, 0x13, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x64, 0x75, 0x61,
	0x6c, 0x5f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x44, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x63, 0x6b,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x70, 0x75, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x70, 0x75, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x8b, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x68, 0x75, 0x62, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0x98, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x4e, 0x45,
	0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x4e,
	0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x4e, 0x45,
	0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xe0, 0x01, 0x0a, 0x13, 0x63,
	0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x42, 0x15, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x52, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61,
	0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63,
	0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_network_class_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_network_class_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_osac_private_v1_network_class_type_proto_goTypes = []any{
	(NetworkClassState)(0),           // 0: osac.private.v1.NetworkClassState
	(*NetworkClass)(nil),             // 1: osac.private.v1.NetworkClass
	(*NetworkClassSpec)(nil),         // 2: osac.private.v1.NetworkClassSpec
	(*NetworkDefaults)(nil),          // 3: osac.private.v1.NetworkDefaults
	(*NetworkClassConstraints)(nil),  // 4: osac.private.v1.NetworkClassConstraints
	(*NetworkClassCapabilities)(nil), // 5: osac.private.v1.NetworkClassCapabilities
	(*NetworkClassStatus)(nil),       // 6: osac.private.v1.NetworkClassStatus
	(*Metadata)(nil),                 // 7: osac.private.v1.Metadata
	(*SecurityRule)(nil),             // 8: osac.private.v1.SecurityRule
}
var file_osac_private_v1_network_class_type_proto_depIdxs = []int32{
	7, // 0: osac.private.v1.NetworkClass.metadata:type_name -> osac.private.v1.Metadata
	4, // 1: osac.private.v1.NetworkClass.constraints:type_name -> osac.private.v1.NetworkClassConstraints
	5, // 2: osac.private.v1.NetworkClass.capabilities:type_name -> osac.private.v1.NetworkClassCapabilities
	6, // 3: osac.private.v1.NetworkClass.status:type_name -> osac.private.v1.NetworkClassStatus
	2, // 4: osac.private.v1.NetworkClass.spec:type_name -> osac.private.v1.NetworkClassSpec
	3, // 5: osac.private.v1.NetworkClassSpec.defaults:type_name -> osac.private.v1.NetworkDefaults
	8, // 6: osac.private.v1.NetworkDefaults.ingress_rules:type_name -> osac.private.v1.SecurityRule
	8, // 7: osac.private.v1.NetworkDefaults.egress_rules:type_name -> osac.private.v1.SecurityRule
	0, // 8: osac.private.v1.NetworkClassStatus.state:type_name -> osac.private.v1.NetworkClassState
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_osac_private_v1_network_class_type_proto_init() }
func file_osac_private_v1_network_class_type_proto_init() {
	if File_osac_private_v1_network_class_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_security_group_type_proto_init()
	file_osac_private_v1_network_class_type_proto_msgTypes[0].OneofWrappers = []any{}
	file_osac_private_v1_network_class_type_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_network_class_type_proto_rawDesc), len(file_osac_private_v1_network_class_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_network_class_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_network_class_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_network_class_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_network_class_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_network_class_type_proto = out.File
	file_osac_private_v1_network_class_type_proto_goTypes = nil
	file_osac_private_v1_network_class_type_proto_depIdxs = nil
}
