//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/storage_tiers_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageTiers_List_FullMethodName   = "/osac.private.v1.StorageTiers/List"
	StorageTiers_Get_FullMethodName    = "/osac.private.v1.StorageTiers/Get"
	StorageTiers_Create_FullMethodName = "/osac.private.v1.StorageTiers/Create"
	StorageTiers_Update_FullMethodName = "/osac.private.v1.StorageTiers/Update"
	StorageTiers_Delete_FullMethodName = "/osac.private.v1.StorageTiers/Delete"
	StorageTiers_Signal_FullMethodName = "/osac.private.v1.StorageTiers/Signal"
)

// StorageTiersClient is the client API for StorageTiers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageTiersClient interface {
	// Retrieves the list of storage tiers.
	List(ctx context.Context, in *StorageTiersListRequest, opts ...grpc.CallOption) (*StorageTiersListResponse, error)
	// Retrieves the details of one specific storage tier.
	Get(ctx context.Context, in *StorageTiersGetRequest, opts ...grpc.CallOption) (*StorageTiersGetResponse, error)
	// Creates a new storage tier.
	Create(ctx context.Context, in *StorageTiersCreateRequest, opts ...grpc.CallOption) (*StorageTiersCreateResponse, error)
	// Updates an existing storage tier.
	Update(ctx context.Context, in *StorageTiersUpdateRequest, opts ...grpc.CallOption) (*StorageTiersUpdateResponse, error)
	// Deletes a storage tier.
	Delete(ctx context.Context, in *StorageTiersDeleteRequest, opts ...grpc.CallOption) (*StorageTiersDeleteResponse, error)
	// Signal is required by the generic server infrastructure but is not implemented for StorageTier
	// (no reconciler). Calls return UNIMPLEMENTED.
	Signal(ctx context.Context, in *StorageTiersSignalRequest, opts ...grpc.CallOption) (*StorageTiersSignalResponse, error)
}

type storageTiersClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageTiersClient(cc grpc.ClientConnInterface) StorageTiersClient {
	return &storageTiersClient{cc}
}

func (c *storageTiersClient) List(ctx context.Context, in *StorageTiersListRequest, opts ...grpc.CallOption) (*StorageTiersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersListResponse)
	err := c.cc.Invoke(ctx, StorageTiers_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageTiersClient) Get(ctx context.Context, in *StorageTiersGetRequest, opts ...grpc.CallOption) (*StorageTiersGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersGetResponse)
	err := c.cc.Invoke(ctx, StorageTiers_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageTiersClient) Create(ctx context.Context, in *StorageTiersCreateRequest, opts ...grpc.CallOption) (*StorageTiersCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersCreateResponse)
	err := c.cc.Invoke(ctx, StorageTiers_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageTiersClient) Update(ctx context.Context, in *StorageTiersUpdateRequest, opts ...grpc.CallOption) (*StorageTiersUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersUpdateResponse)
	err := c.cc.Invoke(ctx, StorageTiers_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageTiersClient) Delete(ctx context.Context, in *StorageTiersDeleteRequest, opts ...grpc.CallOption) (*StorageTiersDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersDeleteResponse)
	err := c.cc.Invoke(ctx, StorageTiers_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageTiersClient) Signal(ctx context.Context, in *StorageTiersSignalRequest, opts ...grpc.CallOption) (*StorageTiersSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageTiersSignalResponse)
	err := c.cc.Invoke(ctx, StorageTiers_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageTiersServer is the server API for StorageTiers service.
// All implementations must embed UnimplementedStorageTiersServer
// for forward compatibility.
type StorageTiersServer interface {
	// Retrieves the list of storage tiers.
	List(context.Context, *StorageTiersListRequest) (*StorageTiersListResponse, error)
	// Retrieves the details of one specific storage tier.
	Get(context.Context, *StorageTiersGetRequest) (*StorageTiersGetResponse, error)
	// Creates a new storage tier.
	Create(context.Context, *StorageTiersCreateRequest) (*StorageTiersCreateResponse, error)
	// Updates an existing storage tier.
	Update(context.Context, *StorageTiersUpdateRequest) (*StorageTiersUpdateResponse, error)
	// Deletes a storage tier.
	Delete(context.Context, *StorageTiersDeleteRequest) (*StorageTiersDeleteResponse, error)
	// Signal is required by the generic server infrastructure but is not implemented for StorageTier
	// (no reconciler). Calls return UNIMPLEMENTED.
	Signal(context.Context, *StorageTiersSignalRequest) (*StorageTiersSignalResponse, error)
	mustEmbedUnimplementedStorageTiersServer()
}

// UnimplementedStorageTiersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageTiersServer struct{}

func (UnimplementedStorageTiersServer) List(context.Context, *StorageTiersListRequest) (*StorageTiersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStorageTiersServer) Get(context.Context, *StorageTiersGetRequest) (*StorageTiersGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStorageTiersServer) Create(context.Context, *StorageTiersCreateRequest) (*StorageTiersCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStorageTiersServer) Update(context.Context, *StorageTiersUpdateRequest) (*StorageTiersUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStorageTiersServer) Delete(context.Context, *StorageTiersDeleteRequest) (*StorageTiersDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStorageTiersServer) Signal(context.Context, *StorageTiersSignalRequest) (*StorageTiersSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedStorageTiersServer) mustEmbedUnimplementedStorageTiersServer() {}
func (UnimplementedStorageTiersServer) testEmbeddedByValue()                      {}

// UnsafeStorageTiersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageTiersServer will
// result in compilation errors.
type UnsafeStorageTiersServer interface {
	mustEmbedUnimplementedStorageTiersServer()
}

func RegisterStorageTiersServer(s grpc.ServiceRegistrar, srv StorageTiersServer) {
	// If the following call pancis, it indicates UnimplementedStorageTiersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageTiers_ServiceDesc, srv)
}

func _StorageTiers_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).List(ctx, req.(*StorageTiersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageTiers_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).Get(ctx, req.(*StorageTiersGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageTiers_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).Create(ctx, req.(*StorageTiersCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageTiers_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).Update(ctx, req.(*StorageTiersUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageTiers_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).Delete(ctx, req.(*StorageTiersDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageTiers_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageTiersSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageTiersServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageTiers_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageTiersServer).Signal(ctx, req.(*StorageTiersSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageTiers_ServiceDesc is the grpc.ServiceDesc for StorageTiers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageTiers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.StorageTiers",
	HandlerType: (*StorageTiersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _StorageTiers_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StorageTiers_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StorageTiers_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StorageTiers_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StorageTiers_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _StorageTiers_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/storage_tiers_service.proto",
}
