// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/auth (interfaces: UserIDResolver)
//
// Generated by this command:
//
//	mockgen -destination=internal/auth/user_id_resolver_mock.go -package=auth github.com/osac-project/fulfillment-service/internal/auth UserIDResolver
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserIDResolver is a mock of UserIDResolver interface.
type MockUserIDResolver struct {
	ctrl     *gomock.Controller
	recorder *MockUserIDResolverMockRecorder
	isgomock struct{}
}

// MockUserIDResolverMockRecorder is the mock recorder for MockUserIDResolver.
type MockUserIDResolverMockRecorder struct {
	mock *MockUserIDResolver
}

// NewMockUserIDResolver creates a new mock instance.
func NewMockUserIDResolver(ctrl *gomock.Controller) *MockUserIDResolver {
	mock := &MockUserIDResolver{ctrl: ctrl}
	mock.recorder = &MockUserIDResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIDResolver) EXPECT() *MockUserIDResolverMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockUserIDResolver) GetID(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserIDResolverMockRecorder) GetID(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserIDResolver)(nil).GetID), ctx, username)
}
