//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/compute_instance_template_type.proto

//go:build protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A compute instance template defines a type of compute instance that can be created by the user. Note that the user doesn't create these
// templates: the system provides a collection of them, and the user chooses one.
type ComputeInstanceTemplate struct {
	state                   protoimpl.MessageState                         `protogen:"opaque.v1"`
	xxx_hidden_Id           string                                         `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata     *Metadata                                      `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Title        string                                         `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Description  string                                         `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_Parameters   *[]*ComputeInstanceTemplateParameterDefinition `protobuf:"bytes,5,rep,name=parameters,proto3"`
	xxx_hidden_SpecDefaults *ComputeInstanceTemplateSpecDefaults           `protobuf:"bytes,6,opt,name=spec_defaults,json=specDefaults,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ComputeInstanceTemplate) Reset() {
	*x = ComputeInstanceTemplate{}
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplate) ProtoMessage() {}

func (x *ComputeInstanceTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplate) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ComputeInstanceTemplate) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetParameters() []*ComputeInstanceTemplateParameterDefinition {
	if x != nil {
		if x.xxx_hidden_Parameters != nil {
			return *x.xxx_hidden_Parameters
		}
	}
	return nil
}

func (x *ComputeInstanceTemplate) GetSpecDefaults() *ComputeInstanceTemplateSpecDefaults {
	if x != nil {
		return x.xxx_hidden_SpecDefaults
	}
	return nil
}

func (x *ComputeInstanceTemplate) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ComputeInstanceTemplate) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ComputeInstanceTemplate) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *ComputeInstanceTemplate) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ComputeInstanceTemplate) SetParameters(v []*ComputeInstanceTemplateParameterDefinition) {
	x.xxx_hidden_Parameters = &v
}

func (x *ComputeInstanceTemplate) SetSpecDefaults(v *ComputeInstanceTemplateSpecDefaults) {
	x.xxx_hidden_SpecDefaults = v
}

func (x *ComputeInstanceTemplate) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ComputeInstanceTemplate) HasSpecDefaults() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SpecDefaults != nil
}

func (x *ComputeInstanceTemplate) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ComputeInstanceTemplate) ClearSpecDefaults() {
	x.xxx_hidden_SpecDefaults = nil
}

type ComputeInstanceTemplate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the template.
	Id       string
	Metadata *Metadata
	// Human friendly short description of the template, only a few words, suitable for displaying in one single line on a
	// UI or CLI.
	Title string
	// Human friendly long description of the template, using Markdown format.
	Description string
	// Definitions of the parameters that can be used to customize the template.
	//
	// Note that these are only the *definitions* of the parameters, not the actual values. The actual values are in the
	// `spec.template_parameters` field of the compute instance.
	Parameters []*ComputeInstanceTemplateParameterDefinition
	// Default values for compute instance spec fields. When a user creates a
	// compute instance without setting these fields, these values are applied.
	//
	// User-provided spec field values always override these defaults.
	SpecDefaults *ComputeInstanceTemplateSpecDefaults
}

func (b0 ComputeInstanceTemplate_builder) Build() *ComputeInstanceTemplate {
	m0 := &ComputeInstanceTemplate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Parameters = &b.Parameters
	x.xxx_hidden_SpecDefaults = b.SpecDefaults
	return m0
}

// Contains type and documentation of a template parameter.
type ComputeInstanceTemplateParameterDefinition struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Title       string                 `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Required    bool                   `protobuf:"varint,4,opt,name=required,proto3"`
	xxx_hidden_Type        string                 `protobuf:"bytes,5,opt,name=type,proto3"`
	xxx_hidden_Default     *anypb.Any             `protobuf:"bytes,6,opt,name=default,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ComputeInstanceTemplateParameterDefinition) Reset() {
	*x = ComputeInstanceTemplateParameterDefinition{}
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplateParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplateParameterDefinition) ProtoMessage() {}

func (x *ComputeInstanceTemplateParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplateParameterDefinition) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetRequired() bool {
	if x != nil {
		return x.xxx_hidden_Required
	}
	return false
}

func (x *ComputeInstanceTemplateParameterDefinition) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetDefault() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Default
	}
	return nil
}

func (x *ComputeInstanceTemplateParameterDefinition) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetRequired(v bool) {
	x.xxx_hidden_Required = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetDefault(v *anypb.Any) {
	x.xxx_hidden_Default = v
}

func (x *ComputeInstanceTemplateParameterDefinition) HasDefault() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Default != nil
}

func (x *ComputeInstanceTemplateParameterDefinition) ClearDefault() {
	x.xxx_hidden_Default = nil
}

type ComputeInstanceTemplateParameterDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the parameter.
	//
	// This is the name that should be used in the `template_parameters` field of the compute instance to assign a value to the
	// parameter.
	Name string
	// Human friendly short description of the parameter, only a few words, suitable for displaying in one single line on
	// a UI or CLI.
	Title string
	// Human friendly description of the parameter, using Markdown format.
	Description string
	// Indicates if this parameter is required or optional.
	//
	// Values for required parameters must be included when creating the compute instance, otherwise it will be rejected.
	//
	// Note that there may be other dependencies between parameters which may cause a compute instance to be rejected. For example,
	// the allowed values of a parameter may depend on the value of another parameter. That kind of information will be in
	// the `description` field.
	Required bool
	// Type of the parameter.
	//
	// The possible values are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	//
	// When using the HTTP+JSON version of the API the value provided in the `template_parameters` field of the compute instance
	// must be represented as documented in the (ProtoJSON format document)[https://protobuf.dev/programming-guides/json].
	Type string
	// Default value for optional parameters.
	Default *anypb.Any
}

func (b0 ComputeInstanceTemplateParameterDefinition_builder) Build() *ComputeInstanceTemplateParameterDefinition {
	m0 := &ComputeInstanceTemplateParameterDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Required = b.Required
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Default = b.Default
	return m0
}

// Default values for compute instance spec fields.
type ComputeInstanceTemplateSpecDefaults struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Image        *ComputeInstanceImage  `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
	xxx_hidden_BootDisk     *ComputeInstanceDisk   `protobuf:"bytes,4,opt,name=boot_disk,json=bootDisk,proto3,oneof"`
	xxx_hidden_RunStrategy  *string                `protobuf:"bytes,5,opt,name=run_strategy,json=runStrategy,proto3,oneof"`
	xxx_hidden_InstanceType *string                `protobuf:"bytes,6,opt,name=instance_type,json=instanceType,proto3,oneof"`
	xxx_hidden_IsWindows    bool                   `protobuf:"varint,7,opt,name=is_windows,json=isWindows,proto3,oneof"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ComputeInstanceTemplateSpecDefaults) Reset() {
	*x = ComputeInstanceTemplateSpecDefaults{}
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplateSpecDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplateSpecDefaults) ProtoMessage() {}

func (x *ComputeInstanceTemplateSpecDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_template_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplateSpecDefaults) GetImage() *ComputeInstanceImage {
	if x != nil {
		return x.xxx_hidden_Image
	}
	return nil
}

func (x *ComputeInstanceTemplateSpecDefaults) GetBootDisk() *ComputeInstanceDisk {
	if x != nil {
		return x.xxx_hidden_BootDisk
	}
	return nil
}

func (x *ComputeInstanceTemplateSpecDefaults) GetRunStrategy() string {
	if x != nil {
		if x.xxx_hidden_RunStrategy != nil {
			return *x.xxx_hidden_RunStrategy
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceTemplateSpecDefaults) GetInstanceType() string {
	if x != nil {
		if x.xxx_hidden_InstanceType != nil {
			return *x.xxx_hidden_InstanceType
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceTemplateSpecDefaults) GetIsWindows() bool {
	if x != nil {
		return x.xxx_hidden_IsWindows
	}
	return false
}

func (x *ComputeInstanceTemplateSpecDefaults) SetImage(v *ComputeInstanceImage) {
	x.xxx_hidden_Image = v
}

func (x *ComputeInstanceTemplateSpecDefaults) SetBootDisk(v *ComputeInstanceDisk) {
	x.xxx_hidden_BootDisk = v
}

func (x *ComputeInstanceTemplateSpecDefaults) SetRunStrategy(v string) {
	x.xxx_hidden_RunStrategy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ComputeInstanceTemplateSpecDefaults) SetInstanceType(v string) {
	x.xxx_hidden_InstanceType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ComputeInstanceTemplateSpecDefaults) SetIsWindows(v bool) {
	x.xxx_hidden_IsWindows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ComputeInstanceTemplateSpecDefaults) HasImage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Image != nil
}

func (x *ComputeInstanceTemplateSpecDefaults) HasBootDisk() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BootDisk != nil
}

func (x *ComputeInstanceTemplateSpecDefaults) HasRunStrategy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ComputeInstanceTemplateSpecDefaults) HasInstanceType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ComputeInstanceTemplateSpecDefaults) HasIsWindows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ComputeInstanceTemplateSpecDefaults) ClearImage() {
	x.xxx_hidden_Image = nil
}

func (x *ComputeInstanceTemplateSpecDefaults) ClearBootDisk() {
	x.xxx_hidden_BootDisk = nil
}

func (x *ComputeInstanceTemplateSpecDefaults) ClearRunStrategy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RunStrategy = nil
}

func (x *ComputeInstanceTemplateSpecDefaults) ClearInstanceType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_InstanceType = nil
}

func (x *ComputeInstanceTemplateSpecDefaults) ClearIsWindows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IsWindows = false
}

type ComputeInstanceTemplateSpecDefaults_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Default image configuration.
	Image *ComputeInstanceImage
	// Default boot disk configuration.
	BootDisk *ComputeInstanceDisk
	// Default run strategy.
	RunStrategy *string
	// Default instance type name. Specifies the default compute configuration for instances
	// created from this template.
	InstanceType *string
	// Default guest OS type. When true, the VM runs Windows. When false or omitted, the VM runs Linux.
	IsWindows *bool
}

func (b0 ComputeInstanceTemplateSpecDefaults_builder) Build() *ComputeInstanceTemplateSpecDefaults {
	m0 := &ComputeInstanceTemplateSpecDefaults{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Image = b.Image
	x.xxx_hidden_BootDisk = b.BootDisk
	if b.RunStrategy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_RunStrategy = b.RunStrategy
	}
	if b.InstanceType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_InstanceType = b.InstanceType
	}
	if b.IsWindows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_IsWindows = *b.IsWindows
	}
	return m0
}

var File_osac_public_v1_compute_instance_template_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_compute_instance_template_type_proto_rawDesc = string([]byte{
	0x0a, 0x33, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x2a, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6f, 0x73,
	0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcd, 0x02, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x58, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x52, 0x0c, 0x73, 0x70, 0x65, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73,
	0x22, 0xd8, 0x01, 0x0a, 0x2a, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x8c, 0x03, 0x0a, 0x23,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x45, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x73,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x48, 0x01, 0x52, 0x08,
	0x62, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x72,
	0x75, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x02, 0x52, 0x0b, 0x72, 0x75, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x04, 0x52, 0x09, 0x69, 0x73, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x75,
	0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x69, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10,
	0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67, 0x69, 0x62, 0x42, 0xe4, 0x01, 0x0a, 0x12, 0x63,
	0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x42, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e,
	0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_compute_instance_template_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_public_v1_compute_instance_template_type_proto_goTypes = []any{
	(*ComputeInstanceTemplate)(nil),                    // 0: osac.public.v1.ComputeInstanceTemplate
	(*ComputeInstanceTemplateParameterDefinition)(nil), // 1: osac.public.v1.ComputeInstanceTemplateParameterDefinition
	(*ComputeInstanceTemplateSpecDefaults)(nil),        // 2: osac.public.v1.ComputeInstanceTemplateSpecDefaults
	(*Metadata)(nil),             // 3: osac.public.v1.Metadata
	(*anypb.Any)(nil),            // 4: google.protobuf.Any
	(*ComputeInstanceImage)(nil), // 5: osac.public.v1.ComputeInstanceImage
	(*ComputeInstanceDisk)(nil),  // 6: osac.public.v1.ComputeInstanceDisk
}
var file_osac_public_v1_compute_instance_template_type_proto_depIdxs = []int32{
	3, // 0: osac.public.v1.ComputeInstanceTemplate.metadata:type_name -> osac.public.v1.Metadata
	1, // 1: osac.public.v1.ComputeInstanceTemplate.parameters:type_name -> osac.public.v1.ComputeInstanceTemplateParameterDefinition
	2, // 2: osac.public.v1.ComputeInstanceTemplate.spec_defaults:type_name -> osac.public.v1.ComputeInstanceTemplateSpecDefaults
	4, // 3: osac.public.v1.ComputeInstanceTemplateParameterDefinition.default:type_name -> google.protobuf.Any
	5, // 4: osac.public.v1.ComputeInstanceTemplateSpecDefaults.image:type_name -> osac.public.v1.ComputeInstanceImage
	6, // 5: osac.public.v1.ComputeInstanceTemplateSpecDefaults.boot_disk:type_name -> osac.public.v1.ComputeInstanceDisk
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_osac_public_v1_compute_instance_template_type_proto_init() }
func file_osac_public_v1_compute_instance_template_type_proto_init() {
	if File_osac_public_v1_compute_instance_template_type_proto != nil {
		return
	}
	file_osac_public_v1_compute_instance_type_proto_init()
	file_osac_public_v1_metadata_type_proto_init()
	file_osac_public_v1_compute_instance_template_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_compute_instance_template_type_proto_rawDesc), len(file_osac_public_v1_compute_instance_template_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_compute_instance_template_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_compute_instance_template_type_proto_depIdxs,
		MessageInfos:      file_osac_public_v1_compute_instance_template_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_compute_instance_template_type_proto = out.File
	file_osac_public_v1_compute_instance_template_type_proto_goTypes = nil
	file_osac_public_v1_compute_instance_template_type_proto_depIdxs = nil
}
