//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/console_service.proto

//go:build protoopaque

package publicv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of resource to connect a console to.
type ConsoleResourceType int32

const (
	ConsoleResourceType_CONSOLE_RESOURCE_TYPE_UNSPECIFIED      ConsoleResourceType = 0
	ConsoleResourceType_CONSOLE_RESOURCE_TYPE_COMPUTE_INSTANCE ConsoleResourceType = 1
	ConsoleResourceType_CONSOLE_RESOURCE_TYPE_HOST             ConsoleResourceType = 2
)

// Enum value maps for ConsoleResourceType.
var (
	ConsoleResourceType_name = map[int32]string{
		0: "CONSOLE_RESOURCE_TYPE_UNSPECIFIED",
		1: "CONSOLE_RESOURCE_TYPE_COMPUTE_INSTANCE",
		2: "CONSOLE_RESOURCE_TYPE_HOST",
	}
	ConsoleResourceType_value = map[string]int32{
		"CONSOLE_RESOURCE_TYPE_UNSPECIFIED":      0,
		"CONSOLE_RESOURCE_TYPE_COMPUTE_INSTANCE": 1,
		"CONSOLE_RESOURCE_TYPE_HOST":             2,
	}
)

func (x ConsoleResourceType) Enum() *ConsoleResourceType {
	p := new(ConsoleResourceType)
	*p = x
	return p
}

func (x ConsoleResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_console_service_proto_enumTypes[0].Descriptor()
}

func (ConsoleResourceType) Type() protoreflect.EnumType {
	return &file_osac_public_v1_console_service_proto_enumTypes[0]
}

func (x ConsoleResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Type of console connection.
type ConsoleType int32

const (
	ConsoleType_CONSOLE_TYPE_UNSPECIFIED ConsoleType = 0
	ConsoleType_CONSOLE_TYPE_SERIAL      ConsoleType = 1
	ConsoleType_CONSOLE_TYPE_VNC         ConsoleType = 2
)

// Enum value maps for ConsoleType.
var (
	ConsoleType_name = map[int32]string{
		0: "CONSOLE_TYPE_UNSPECIFIED",
		1: "CONSOLE_TYPE_SERIAL",
		2: "CONSOLE_TYPE_VNC",
	}
	ConsoleType_value = map[string]int32{
		"CONSOLE_TYPE_UNSPECIFIED": 0,
		"CONSOLE_TYPE_SERIAL":      1,
		"CONSOLE_TYPE_VNC":         2,
	}
)

func (x ConsoleType) Enum() *ConsoleType {
	p := new(ConsoleType)
	*p = x
	return p
}

func (x ConsoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_console_service_proto_enumTypes[1].Descriptor()
}

func (ConsoleType) Type() protoreflect.EnumType {
	return &file_osac_public_v1_console_service_proto_enumTypes[1]
}

func (x ConsoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// State of the console connection.
type ConsoleConnectionState int32

const (
	ConsoleConnectionState_CONSOLE_CONNECTION_STATE_UNSPECIFIED  ConsoleConnectionState = 0
	ConsoleConnectionState_CONSOLE_CONNECTION_STATE_CONNECTING   ConsoleConnectionState = 1
	ConsoleConnectionState_CONSOLE_CONNECTION_STATE_CONNECTED    ConsoleConnectionState = 2
	ConsoleConnectionState_CONSOLE_CONNECTION_STATE_DISCONNECTED ConsoleConnectionState = 3
	ConsoleConnectionState_CONSOLE_CONNECTION_STATE_ERROR        ConsoleConnectionState = 4
)

// Enum value maps for ConsoleConnectionState.
var (
	ConsoleConnectionState_name = map[int32]string{
		0: "CONSOLE_CONNECTION_STATE_UNSPECIFIED",
		1: "CONSOLE_CONNECTION_STATE_CONNECTING",
		2: "CONSOLE_CONNECTION_STATE_CONNECTED",
		3: "CONSOLE_CONNECTION_STATE_DISCONNECTED",
		4: "CONSOLE_CONNECTION_STATE_ERROR",
	}
	ConsoleConnectionState_value = map[string]int32{
		"CONSOLE_CONNECTION_STATE_UNSPECIFIED":  0,
		"CONSOLE_CONNECTION_STATE_CONNECTING":   1,
		"CONSOLE_CONNECTION_STATE_CONNECTED":    2,
		"CONSOLE_CONNECTION_STATE_DISCONNECTED": 3,
		"CONSOLE_CONNECTION_STATE_ERROR":        4,
	}
)

func (x ConsoleConnectionState) Enum() *ConsoleConnectionState {
	p := new(ConsoleConnectionState)
	*p = x
	return p
}

func (x ConsoleConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_console_service_proto_enumTypes[2].Descriptor()
}

func (ConsoleConnectionState) Type() protoreflect.EnumType {
	return &file_osac_public_v1_console_service_proto_enumTypes[2]
}

func (x ConsoleConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Client-to-server message for the bidirectional console stream.
type ConsoleConnectRequest struct {
	state              protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Payload isConsoleConnectRequest_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsoleConnectRequest) Reset() {
	*x = ConsoleConnectRequest{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleConnectRequest) ProtoMessage() {}

func (x *ConsoleConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleConnectRequest) GetInit() *ConsoleConnectInit {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ConsoleConnectRequest) GetInput() *ConsoleInput {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ConsoleConnectRequest) GetResize() *ConsoleResize {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ConsoleConnectRequest) SetInit(v *ConsoleConnectInit) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &consoleConnectRequest_Init{v}
}

func (x *ConsoleConnectRequest) SetInput(v *ConsoleInput) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &consoleConnectRequest_Input{v}
}

func (x *ConsoleConnectRequest) SetResize(v *ConsoleResize) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &consoleConnectRequest_Resize{v}
}

func (x *ConsoleConnectRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *ConsoleConnectRequest) HasInit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Init)
	return ok
}

func (x *ConsoleConnectRequest) HasInput() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Input)
	return ok
}

func (x *ConsoleConnectRequest) HasResize() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Resize)
	return ok
}

func (x *ConsoleConnectRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *ConsoleConnectRequest) ClearInit() {
	if _, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Init); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *ConsoleConnectRequest) ClearInput() {
	if _, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Input); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *ConsoleConnectRequest) ClearResize() {
	if _, ok := x.xxx_hidden_Payload.(*consoleConnectRequest_Resize); ok {
		x.xxx_hidden_Payload = nil
	}
}

const ConsoleConnectRequest_Payload_not_set_case case_ConsoleConnectRequest_Payload = 0
const ConsoleConnectRequest_Init_case case_ConsoleConnectRequest_Payload = 1
const ConsoleConnectRequest_Input_case case_ConsoleConnectRequest_Payload = 2
const ConsoleConnectRequest_Resize_case case_ConsoleConnectRequest_Payload = 3

func (x *ConsoleConnectRequest) WhichPayload() case_ConsoleConnectRequest_Payload {
	if x == nil {
		return ConsoleConnectRequest_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *consoleConnectRequest_Init:
		return ConsoleConnectRequest_Init_case
	case *consoleConnectRequest_Input:
		return ConsoleConnectRequest_Input_case
	case *consoleConnectRequest_Resize:
		return ConsoleConnectRequest_Resize_case
	default:
		return ConsoleConnectRequest_Payload_not_set_case
	}
}

type ConsoleConnectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Init   *ConsoleConnectInit
	Input  *ConsoleInput
	Resize *ConsoleResize
	// -- end of xxx_hidden_Payload
}

func (b0 ConsoleConnectRequest_builder) Build() *ConsoleConnectRequest {
	m0 := &ConsoleConnectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Init != nil {
		x.xxx_hidden_Payload = &consoleConnectRequest_Init{b.Init}
	}
	if b.Input != nil {
		x.xxx_hidden_Payload = &consoleConnectRequest_Input{b.Input}
	}
	if b.Resize != nil {
		x.xxx_hidden_Payload = &consoleConnectRequest_Resize{b.Resize}
	}
	return m0
}

type case_ConsoleConnectRequest_Payload protoreflect.FieldNumber

func (x case_ConsoleConnectRequest_Payload) String() string {
	md := file_osac_public_v1_console_service_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isConsoleConnectRequest_Payload interface {
	isConsoleConnectRequest_Payload()
}

type consoleConnectRequest_Init struct {
	Init *ConsoleConnectInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type consoleConnectRequest_Input struct {
	Input *ConsoleInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type consoleConnectRequest_Resize struct {
	Resize *ConsoleResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*consoleConnectRequest_Init) isConsoleConnectRequest_Payload() {}

func (*consoleConnectRequest_Input) isConsoleConnectRequest_Payload() {}

func (*consoleConnectRequest_Resize) isConsoleConnectRequest_Payload() {}

// Initialization message. Must be the first message sent by the client.
type ConsoleConnectInit struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceType ConsoleResourceType    `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=osac.public.v1.ConsoleResourceType"`
	xxx_hidden_ResourceId   string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3"`
	xxx_hidden_Type         ConsoleType            `protobuf:"varint,3,opt,name=type,proto3,enum=osac.public.v1.ConsoleType"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConsoleConnectInit) Reset() {
	*x = ConsoleConnectInit{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleConnectInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleConnectInit) ProtoMessage() {}

func (x *ConsoleConnectInit) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleConnectInit) GetResourceType() ConsoleResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return ConsoleResourceType_CONSOLE_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ConsoleConnectInit) GetResourceId() string {
	if x != nil {
		return x.xxx_hidden_ResourceId
	}
	return ""
}

func (x *ConsoleConnectInit) GetType() ConsoleType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ConsoleType_CONSOLE_TYPE_UNSPECIFIED
}

func (x *ConsoleConnectInit) SetResourceType(v ConsoleResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *ConsoleConnectInit) SetResourceId(v string) {
	x.xxx_hidden_ResourceId = v
}

func (x *ConsoleConnectInit) SetType(v ConsoleType) {
	x.xxx_hidden_Type = v
}

type ConsoleConnectInit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceType ConsoleResourceType
	ResourceId   string
	Type         ConsoleType
}

func (b0 ConsoleConnectInit_builder) Build() *ConsoleConnectInit {
	m0 := &ConsoleConnectInit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceType = b.ResourceType
	x.xxx_hidden_ResourceId = b.ResourceId
	x.xxx_hidden_Type = b.Type
	return m0
}

// Terminal input data from the client.
type ConsoleInput struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data []byte                 `protobuf:"bytes,1,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsoleInput) Reset() {
	*x = ConsoleInput{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInput) ProtoMessage() {}

func (x *ConsoleInput) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleInput) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ConsoleInput) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type ConsoleInput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 ConsoleInput_builder) Build() *ConsoleInput {
	m0 := &ConsoleInput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

// Terminal resize event. No-op for serial consoles; forward-compatible for VNC.
type ConsoleResize struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Width  uint32                 `protobuf:"varint,1,opt,name=width,proto3"`
	xxx_hidden_Height uint32                 `protobuf:"varint,2,opt,name=height,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsoleResize) Reset() {
	*x = ConsoleResize{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleResize) ProtoMessage() {}

func (x *ConsoleResize) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleResize) GetWidth() uint32 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *ConsoleResize) GetHeight() uint32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *ConsoleResize) SetWidth(v uint32) {
	x.xxx_hidden_Width = v
}

func (x *ConsoleResize) SetHeight(v uint32) {
	x.xxx_hidden_Height = v
}

type ConsoleResize_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Width  uint32
	Height uint32
}

func (b0 ConsoleResize_builder) Build() *ConsoleResize {
	m0 := &ConsoleResize{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Width = b.Width
	x.xxx_hidden_Height = b.Height
	return m0
}

// Server-to-client message for the bidirectional console stream.
type ConsoleConnectResponse struct {
	state              protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Payload isConsoleConnectResponse_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsoleConnectResponse) Reset() {
	*x = ConsoleConnectResponse{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleConnectResponse) ProtoMessage() {}

func (x *ConsoleConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleConnectResponse) GetOutput() *ConsoleOutput {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ConsoleConnectResponse) GetStatus() *ConsoleStatus {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ConsoleConnectResponse) SetOutput(v *ConsoleOutput) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &consoleConnectResponse_Output{v}
}

func (x *ConsoleConnectResponse) SetStatus(v *ConsoleStatus) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &consoleConnectResponse_Status{v}
}

func (x *ConsoleConnectResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *ConsoleConnectResponse) HasOutput() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Output)
	return ok
}

func (x *ConsoleConnectResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Status)
	return ok
}

func (x *ConsoleConnectResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *ConsoleConnectResponse) ClearOutput() {
	if _, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Output); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *ConsoleConnectResponse) ClearStatus() {
	if _, ok := x.xxx_hidden_Payload.(*consoleConnectResponse_Status); ok {
		x.xxx_hidden_Payload = nil
	}
}

const ConsoleConnectResponse_Payload_not_set_case case_ConsoleConnectResponse_Payload = 0
const ConsoleConnectResponse_Output_case case_ConsoleConnectResponse_Payload = 1
const ConsoleConnectResponse_Status_case case_ConsoleConnectResponse_Payload = 2

func (x *ConsoleConnectResponse) WhichPayload() case_ConsoleConnectResponse_Payload {
	if x == nil {
		return ConsoleConnectResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *consoleConnectResponse_Output:
		return ConsoleConnectResponse_Output_case
	case *consoleConnectResponse_Status:
		return ConsoleConnectResponse_Status_case
	default:
		return ConsoleConnectResponse_Payload_not_set_case
	}
}

type ConsoleConnectResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Output *ConsoleOutput
	Status *ConsoleStatus
	// -- end of xxx_hidden_Payload
}

func (b0 ConsoleConnectResponse_builder) Build() *ConsoleConnectResponse {
	m0 := &ConsoleConnectResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Output != nil {
		x.xxx_hidden_Payload = &consoleConnectResponse_Output{b.Output}
	}
	if b.Status != nil {
		x.xxx_hidden_Payload = &consoleConnectResponse_Status{b.Status}
	}
	return m0
}

type case_ConsoleConnectResponse_Payload protoreflect.FieldNumber

func (x case_ConsoleConnectResponse_Payload) String() string {
	md := file_osac_public_v1_console_service_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isConsoleConnectResponse_Payload interface {
	isConsoleConnectResponse_Payload()
}

type consoleConnectResponse_Output struct {
	Output *ConsoleOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type consoleConnectResponse_Status struct {
	Status *ConsoleStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*consoleConnectResponse_Output) isConsoleConnectResponse_Payload() {}

func (*consoleConnectResponse_Status) isConsoleConnectResponse_Payload() {}

// Terminal output data from the compute instance.
type ConsoleOutput struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data []byte                 `protobuf:"bytes,1,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleOutput) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ConsoleOutput) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type ConsoleOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 ConsoleOutput_builder) Build() *ConsoleOutput {
	m0 := &ConsoleOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

// Status update from the server about the console connection.
type ConsoleStatus struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State   ConsoleConnectionState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.public.v1.ConsoleConnectionState"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsoleStatus) Reset() {
	*x = ConsoleStatus{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStatus) ProtoMessage() {}

func (x *ConsoleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleStatus) GetState() ConsoleConnectionState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ConsoleConnectionState_CONSOLE_CONNECTION_STATE_UNSPECIFIED
}

func (x *ConsoleStatus) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *ConsoleStatus) SetState(v ConsoleConnectionState) {
	x.xxx_hidden_State = v
}

func (x *ConsoleStatus) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type ConsoleStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State   ConsoleConnectionState
	Message string
}

func (b0 ConsoleStatus_builder) Build() *ConsoleStatus {
	m0 := &ConsoleStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Message = b.Message
	return m0
}

// Request to check console availability without connecting.
type ConsoleGetAccessRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceType ConsoleResourceType    `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=osac.public.v1.ConsoleResourceType"`
	xxx_hidden_ResourceId   string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConsoleGetAccessRequest) Reset() {
	*x = ConsoleGetAccessRequest{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleGetAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleGetAccessRequest) ProtoMessage() {}

func (x *ConsoleGetAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleGetAccessRequest) GetResourceType() ConsoleResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return ConsoleResourceType_CONSOLE_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ConsoleGetAccessRequest) GetResourceId() string {
	if x != nil {
		return x.xxx_hidden_ResourceId
	}
	return ""
}

func (x *ConsoleGetAccessRequest) SetResourceType(v ConsoleResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *ConsoleGetAccessRequest) SetResourceId(v string) {
	x.xxx_hidden_ResourceId = v
}

type ConsoleGetAccessRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceType ConsoleResourceType
	ResourceId   string
}

func (b0 ConsoleGetAccessRequest_builder) Build() *ConsoleGetAccessRequest {
	m0 := &ConsoleGetAccessRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceType = b.ResourceType
	x.xxx_hidden_ResourceId = b.ResourceId
	return m0
}

// Response with console availability information.
type ConsoleGetAccessResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Available      bool                   `protobuf:"varint,1,opt,name=available,proto3"`
	xxx_hidden_Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3"`
	xxx_hidden_SupportedTypes []ConsoleType          `protobuf:"varint,3,rep,packed,name=supported_types,json=supportedTypes,proto3,enum=osac.public.v1.ConsoleType"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConsoleGetAccessResponse) Reset() {
	*x = ConsoleGetAccessResponse{}
	mi := &file_osac_public_v1_console_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleGetAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleGetAccessResponse) ProtoMessage() {}

func (x *ConsoleGetAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_console_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsoleGetAccessResponse) GetAvailable() bool {
	if x != nil {
		return x.xxx_hidden_Available
	}
	return false
}

func (x *ConsoleGetAccessResponse) GetReason() string {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ""
}

func (x *ConsoleGetAccessResponse) GetSupportedTypes() []ConsoleType {
	if x != nil {
		return x.xxx_hidden_SupportedTypes
	}
	return nil
}

func (x *ConsoleGetAccessResponse) SetAvailable(v bool) {
	x.xxx_hidden_Available = v
}

func (x *ConsoleGetAccessResponse) SetReason(v string) {
	x.xxx_hidden_Reason = v
}

func (x *ConsoleGetAccessResponse) SetSupportedTypes(v []ConsoleType) {
	x.xxx_hidden_SupportedTypes = v
}

type ConsoleGetAccessResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Available      bool
	Reason         string
	SupportedTypes []ConsoleType
}

func (b0 ConsoleGetAccessResponse_builder) Build() *ConsoleGetAccessResponse {
	m0 := &ConsoleGetAccessResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Available = b.Available
	x.xxx_hidden_Reason = b.Reason
	x.xxx_hidden_SupportedTypes = b.SupportedTypes
	return m0
}

var File_osac_public_v1_console_service_proto protoreflect.FileDescriptor

var file_osac_public_v1_console_service_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x37,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x48, 0x0a, 0x0d, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x37, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x23, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x84,
	0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x0f, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e,
	0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x88,
	0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c,
	0x45, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x2a, 0x0a,
	0x26, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49,
	0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4e,
	0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x2a, 0x5a, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x4e, 0x53,
	0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x56, 0x4e, 0x43, 0x10, 0x02, 0x2a, 0xe2, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x24, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x4f,
	0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x29, 0x0a, 0x25, 0x43,
	0x4f, 0x4e, 0x53, 0x4f, 0x4c, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4f, 0x4e, 0x53, 0x4f, 0x4c,
	0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x32, 0x92, 0x02, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x5c, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x12, 0xa8, 0x01, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x42, 0x12, 0x40, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x7b, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x2f, 0x7b, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42,
	0xd7, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63, 0x5c,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_osac_public_v1_console_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_osac_public_v1_console_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_osac_public_v1_console_service_proto_goTypes = []any{
	(ConsoleResourceType)(0),         // 0: osac.public.v1.ConsoleResourceType
	(ConsoleType)(0),                 // 1: osac.public.v1.ConsoleType
	(ConsoleConnectionState)(0),      // 2: osac.public.v1.ConsoleConnectionState
	(*ConsoleConnectRequest)(nil),    // 3: osac.public.v1.ConsoleConnectRequest
	(*ConsoleConnectInit)(nil),       // 4: osac.public.v1.ConsoleConnectInit
	(*ConsoleInput)(nil),             // 5: osac.public.v1.ConsoleInput
	(*ConsoleResize)(nil),            // 6: osac.public.v1.ConsoleResize
	(*ConsoleConnectResponse)(nil),   // 7: osac.public.v1.ConsoleConnectResponse
	(*ConsoleOutput)(nil),            // 8: osac.public.v1.ConsoleOutput
	(*ConsoleStatus)(nil),            // 9: osac.public.v1.ConsoleStatus
	(*ConsoleGetAccessRequest)(nil),  // 10: osac.public.v1.ConsoleGetAccessRequest
	(*ConsoleGetAccessResponse)(nil), // 11: osac.public.v1.ConsoleGetAccessResponse
}
var file_osac_public_v1_console_service_proto_depIdxs = []int32{
	4,  // 0: osac.public.v1.ConsoleConnectRequest.init:type_name -> osac.public.v1.ConsoleConnectInit
	5,  // 1: osac.public.v1.ConsoleConnectRequest.input:type_name -> osac.public.v1.ConsoleInput
	6,  // 2: osac.public.v1.ConsoleConnectRequest.resize:type_name -> osac.public.v1.ConsoleResize
	0,  // 3: osac.public.v1.ConsoleConnectInit.resource_type:type_name -> osac.public.v1.ConsoleResourceType
	1,  // 4: osac.public.v1.ConsoleConnectInit.type:type_name -> osac.public.v1.ConsoleType
	8,  // 5: osac.public.v1.ConsoleConnectResponse.output:type_name -> osac.public.v1.ConsoleOutput
	9,  // 6: osac.public.v1.ConsoleConnectResponse.status:type_name -> osac.public.v1.ConsoleStatus
	2,  // 7: osac.public.v1.ConsoleStatus.state:type_name -> osac.public.v1.ConsoleConnectionState
	0,  // 8: osac.public.v1.ConsoleGetAccessRequest.resource_type:type_name -> osac.public.v1.ConsoleResourceType
	1,  // 9: osac.public.v1.ConsoleGetAccessResponse.supported_types:type_name -> osac.public.v1.ConsoleType
	3,  // 10: osac.public.v1.Console.Connect:input_type -> osac.public.v1.ConsoleConnectRequest
	10, // 11: osac.public.v1.Console.GetAccess:input_type -> osac.public.v1.ConsoleGetAccessRequest
	7,  // 12: osac.public.v1.Console.Connect:output_type -> osac.public.v1.ConsoleConnectResponse
	11, // 13: osac.public.v1.Console.GetAccess:output_type -> osac.public.v1.ConsoleGetAccessResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_osac_public_v1_console_service_proto_init() }
func file_osac_public_v1_console_service_proto_init() {
	if File_osac_public_v1_console_service_proto != nil {
		return
	}
	file_osac_public_v1_console_service_proto_msgTypes[0].OneofWrappers = []any{
		(*consoleConnectRequest_Init)(nil),
		(*consoleConnectRequest_Input)(nil),
		(*consoleConnectRequest_Resize)(nil),
	}
	file_osac_public_v1_console_service_proto_msgTypes[4].OneofWrappers = []any{
		(*consoleConnectResponse_Output)(nil),
		(*consoleConnectResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_console_service_proto_rawDesc), len(file_osac_public_v1_console_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osac_public_v1_console_service_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_console_service_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_console_service_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_console_service_proto_msgTypes,
	}.Build()
	File_osac_public_v1_console_service_proto = out.File
	file_osac_public_v1_console_service_proto_goTypes = nil
	file_osac_public_v1_console_service_proto_depIdxs = nil
}
