//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/identity_provider_type.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityProviderPhase represents the current phase of an identity provider.
type IdentityProviderPhase int32

const (
	// IDENTITY_PROVIDER_PHASE_UNSPECIFIED is the default value.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNSPECIFIED IdentityProviderPhase = 0
	// IDENTITY_PROVIDER_PHASE_READY indicates the IdP is ready and operational.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_READY IdentityProviderPhase = 1
	// IDENTITY_PROVIDER_PHASE_ERROR indicates the IdP is in an error state.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_ERROR IdentityProviderPhase = 2
	// IDENTITY_PROVIDER_PHASE_UNKNOWN indicates the IdP state is unknown.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNKNOWN IdentityProviderPhase = 3
)

// Enum value maps for IdentityProviderPhase.
var (
	IdentityProviderPhase_name = map[int32]string{
		0: "IDENTITY_PROVIDER_PHASE_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_PHASE_READY",
		2: "IDENTITY_PROVIDER_PHASE_ERROR",
		3: "IDENTITY_PROVIDER_PHASE_UNKNOWN",
	}
	IdentityProviderPhase_value = map[string]int32{
		"IDENTITY_PROVIDER_PHASE_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_PHASE_READY":       1,
		"IDENTITY_PROVIDER_PHASE_ERROR":       2,
		"IDENTITY_PROVIDER_PHASE_UNKNOWN":     3,
	}
)

func (x IdentityProviderPhase) Enum() *IdentityProviderPhase {
	p := new(IdentityProviderPhase)
	*p = x
	return p
}

func (x IdentityProviderPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_identity_provider_type_proto_enumTypes[0].Descriptor()
}

func (IdentityProviderPhase) Type() protoreflect.EnumType {
	return &file_osac_public_v1_identity_provider_type_proto_enumTypes[0]
}

func (x IdentityProviderPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// IdentityProviderHealthStatus represents the health status of an identity provider.
type IdentityProviderHealthStatus int32

const (
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED is the default value.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED IdentityProviderHealthStatus = 0
	// IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY indicates the IdP is healthy.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY IdentityProviderHealthStatus = 1
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY indicates the IdP is unhealthy.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY IdentityProviderHealthStatus = 2
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN indicates the health status is unknown.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN IdentityProviderHealthStatus = 3
)

// Enum value maps for IdentityProviderHealthStatus.
var (
	IdentityProviderHealthStatus_name = map[int32]string{
		0: "IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY",
		2: "IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY",
		3: "IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN",
	}
	IdentityProviderHealthStatus_value = map[string]int32{
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY":     1,
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY":   2,
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN":     3,
	}
)

func (x IdentityProviderHealthStatus) Enum() *IdentityProviderHealthStatus {
	p := new(IdentityProviderHealthStatus)
	*p = x
	return p
}

func (x IdentityProviderHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_identity_provider_type_proto_enumTypes[1].Descriptor()
}

func (IdentityProviderHealthStatus) Type() protoreflect.EnumType {
	return &file_osac_public_v1_identity_provider_type_proto_enumTypes[1]
}

func (x IdentityProviderHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// IdentityProvider represents an external identity provider configuration.
// Identity providers enable users to authenticate using their existing corporate credentials
// (LDAP, Active Directory, OIDC, SAML, etc.) rather than managing separate credentials.
type IdentityProvider struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier for this IdP. Immutable after creation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata contains common object metadata.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec is the desired state of the identity provider.
	Spec *IdentityProviderSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Status is the observed state of the identity provider.
	Status        *IdentityProviderStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProvider) Reset() {
	*x = IdentityProvider{}
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProvider) ProtoMessage() {}

func (x *IdentityProvider) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityProvider) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IdentityProvider) GetSpec() *IdentityProviderSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *IdentityProvider) GetStatus() *IdentityProviderStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *IdentityProvider) SetId(v string) {
	x.Id = v
}

func (x *IdentityProvider) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *IdentityProvider) SetSpec(v *IdentityProviderSpec) {
	x.Spec = v
}

func (x *IdentityProvider) SetStatus(v *IdentityProviderStatus) {
	x.Status = v
}

func (x *IdentityProvider) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *IdentityProvider) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *IdentityProvider) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *IdentityProvider) ClearMetadata() {
	x.Metadata = nil
}

func (x *IdentityProvider) ClearSpec() {
	x.Spec = nil
}

func (x *IdentityProvider) ClearStatus() {
	x.Status = nil
}

type IdentityProvider_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this IdP. Immutable after creation.
	Id string
	// Metadata contains common object metadata.
	Metadata *Metadata
	// Spec is the desired state of the identity provider.
	Spec *IdentityProviderSpec
	// Status is the observed state of the identity provider.
	Status *IdentityProviderStatus
}

func (b0 IdentityProvider_builder) Build() *IdentityProvider {
	m0 := &IdentityProvider{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// IdentityProviderSpec represents the desired state of an identity provider.
type IdentityProviderSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Human-friendly short title for this IdP, suitable for displaying in a single line.
	// Example: "Corporate LDAP" or "GitHub SSO"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Human-friendly description explaining the purpose or scope of this IdP.
	// Example: "Primary LDAP server for employee authentication"
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Enabled indicates whether this IdP should be active and available for authentication.
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Provider-specific configuration settings.
	// The type of identity provider is determined by which config field is set.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*IdentityProviderSpec_Oidc
	Config isIdentityProviderSpec_Config `protobuf_oneof:"config"`
	// This field is used to trigger a health check of the identity provider.
	// The user can write any value here; the actual value doesn't matter.
	// The only important thing is that when it changes, the system will eventually
	// initiate a health check and report the result in the status.
	// The user can set this to any string (e.g., a timestamp or random value) to request a new check.
	// Common pattern: use a timestamp or increment a counter when requesting a check.
	HealthCheckTrigger *string `protobuf:"bytes,6,opt,name=health_check_trigger,json=healthCheckTrigger,proto3,oneof" json:"health_check_trigger,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IdentityProviderSpec) Reset() {
	*x = IdentityProviderSpec{}
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderSpec) ProtoMessage() {}

func (x *IdentityProviderSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IdentityProviderSpec) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *IdentityProviderSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IdentityProviderSpec) GetConfig() isIdentityProviderSpec_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *IdentityProviderSpec) GetOidc() *OidcConfig {
	if x != nil {
		if x, ok := x.Config.(*IdentityProviderSpec_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *IdentityProviderSpec) GetHealthCheckTrigger() string {
	if x != nil && x.HealthCheckTrigger != nil {
		return *x.HealthCheckTrigger
	}
	return ""
}

func (x *IdentityProviderSpec) SetTitle(v string) {
	x.Title = v
}

func (x *IdentityProviderSpec) SetDescription(v string) {
	x.Description = &v
}

func (x *IdentityProviderSpec) SetEnabled(v bool) {
	x.Enabled = v
}

func (x *IdentityProviderSpec) SetOidc(v *OidcConfig) {
	if v == nil {
		x.Config = nil
		return
	}
	x.Config = &IdentityProviderSpec_Oidc{v}
}

func (x *IdentityProviderSpec) SetHealthCheckTrigger(v string) {
	x.HealthCheckTrigger = &v
}

func (x *IdentityProviderSpec) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.Description != nil
}

func (x *IdentityProviderSpec) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.Config != nil
}

func (x *IdentityProviderSpec) HasOidc() bool {
	if x == nil {
		return false
	}
	_, ok := x.Config.(*IdentityProviderSpec_Oidc)
	return ok
}

func (x *IdentityProviderSpec) HasHealthCheckTrigger() bool {
	if x == nil {
		return false
	}
	return x.HealthCheckTrigger != nil
}

func (x *IdentityProviderSpec) ClearDescription() {
	x.Description = nil
}

func (x *IdentityProviderSpec) ClearConfig() {
	x.Config = nil
}

func (x *IdentityProviderSpec) ClearOidc() {
	if _, ok := x.Config.(*IdentityProviderSpec_Oidc); ok {
		x.Config = nil
	}
}

func (x *IdentityProviderSpec) ClearHealthCheckTrigger() {
	x.HealthCheckTrigger = nil
}

const IdentityProviderSpec_Config_not_set_case case_IdentityProviderSpec_Config = 0
const IdentityProviderSpec_Oidc_case case_IdentityProviderSpec_Config = 4

func (x *IdentityProviderSpec) WhichConfig() case_IdentityProviderSpec_Config {
	if x == nil {
		return IdentityProviderSpec_Config_not_set_case
	}
	switch x.Config.(type) {
	case *IdentityProviderSpec_Oidc:
		return IdentityProviderSpec_Oidc_case
	default:
		return IdentityProviderSpec_Config_not_set_case
	}
}

type IdentityProviderSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human-friendly short title for this IdP, suitable for displaying in a single line.
	// Example: "Corporate LDAP" or "GitHub SSO"
	Title string
	// Human-friendly description explaining the purpose or scope of this IdP.
	// Example: "Primary LDAP server for employee authentication"
	Description *string
	// Enabled indicates whether this IdP should be active and available for authentication.
	Enabled bool
	// Provider-specific configuration settings.
	// The type of identity provider is determined by which config field is set.

	// Fields of oneof Config:
	// Configuration for OpenID Connect providers.
	Oidc *OidcConfig
	// -- end of Config
	// This field is used to trigger a health check of the identity provider.
	// The user can write any value here; the actual value doesn't matter.
	// The only important thing is that when it changes, the system will eventually
	// initiate a health check and report the result in the status.
	// The user can set this to any string (e.g., a timestamp or random value) to request a new check.
	// Common pattern: use a timestamp or increment a counter when requesting a check.
	HealthCheckTrigger *string
}

func (b0 IdentityProviderSpec_builder) Build() *IdentityProviderSpec {
	m0 := &IdentityProviderSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Title = b.Title
	x.Description = b.Description
	x.Enabled = b.Enabled
	if b.Oidc != nil {
		x.Config = &IdentityProviderSpec_Oidc{b.Oidc}
	}
	x.HealthCheckTrigger = b.HealthCheckTrigger
	return m0
}

type case_IdentityProviderSpec_Config protoreflect.FieldNumber

func (x case_IdentityProviderSpec_Config) String() string {
	md := file_osac_public_v1_identity_provider_type_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isIdentityProviderSpec_Config interface {
	isIdentityProviderSpec_Config()
}

type IdentityProviderSpec_Oidc struct {
	// Configuration for OpenID Connect providers.
	Oidc *OidcConfig `protobuf:"bytes,4,opt,name=oidc,proto3,oneof"`
}

func (*IdentityProviderSpec_Oidc) isIdentityProviderSpec_Config() {}

// OidcConfig contains configuration for OpenID Connect identity providers.
type OidcConfig struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Authorization endpoint URL where users are redirected to authenticate.
	// Example: "https://accounts.google.com/o/oauth2/v2/auth"
	AuthorizationUrl string `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// Token endpoint URL used to exchange authorization codes for access tokens.
	// Example: "https://oauth2.googleapis.com/token"
	TokenUrl string `protobuf:"bytes,2,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	// Client identifier issued by the OIDC provider.
	// This is a public identifier for the application.
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Client secret for authenticating with the OIDC provider.
	// This field is write-only and will never be returned in API responses.
	ClientSecret string `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Issuer URL that identifies the OIDC provider.
	// Used for validating ID tokens. Must match the 'iss' claim in tokens.
	// Example: "https://accounts.google.com"
	Issuer string `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Space-separated list of OAuth scopes to request.
	// Common scopes: "openid profile email"
	// Default: "openid profile email"
	DefaultScopes *string `protobuf:"bytes,6,opt,name=default_scopes,json=defaultScopes,proto3,oneof" json:"default_scopes,omitempty"`
	// UserInfo endpoint URL for retrieving user profile information.
	// If not specified, user info will be extracted from the ID token.
	// Example: "https://openidconnect.googleapis.com/v1/userinfo"
	UserInfoUrl *string `protobuf:"bytes,7,opt,name=user_info_url,json=userInfoUrl,proto3,oneof" json:"user_info_url,omitempty"`
	// JSON Web Key Set (JWKS) URL for obtaining public keys to verify ID token signatures.
	// If not specified, the provider's discovery endpoint will be used.
	// Example: "https://www.googleapis.com/oauth2/v3/certs"
	JwksUrl *string `protobuf:"bytes,8,opt,name=jwks_url,json=jwksUrl,proto3,oneof" json:"jwks_url,omitempty"`
	// Whether to validate ID token signatures using JWKS.
	// Default: true
	ValidateSignature *bool `protobuf:"varint,9,opt,name=validate_signature,json=validateSignature,proto3,oneof" json:"validate_signature,omitempty"`
	// Logout URL where users are redirected after logging out.
	// Example: "https://accounts.google.com/logout"
	LogoutUrl     *string `protobuf:"bytes,10,opt,name=logout_url,json=logoutUrl,proto3,oneof" json:"logout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OidcConfig) Reset() {
	*x = OidcConfig{}
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OidcConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidcConfig) ProtoMessage() {}

func (x *OidcConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OidcConfig) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *OidcConfig) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OidcConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OidcConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OidcConfig) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OidcConfig) GetDefaultScopes() string {
	if x != nil && x.DefaultScopes != nil {
		return *x.DefaultScopes
	}
	return ""
}

func (x *OidcConfig) GetUserInfoUrl() string {
	if x != nil && x.UserInfoUrl != nil {
		return *x.UserInfoUrl
	}
	return ""
}

func (x *OidcConfig) GetJwksUrl() string {
	if x != nil && x.JwksUrl != nil {
		return *x.JwksUrl
	}
	return ""
}

func (x *OidcConfig) GetValidateSignature() bool {
	if x != nil && x.ValidateSignature != nil {
		return *x.ValidateSignature
	}
	return false
}

func (x *OidcConfig) GetLogoutUrl() string {
	if x != nil && x.LogoutUrl != nil {
		return *x.LogoutUrl
	}
	return ""
}

func (x *OidcConfig) SetAuthorizationUrl(v string) {
	x.AuthorizationUrl = v
}

func (x *OidcConfig) SetTokenUrl(v string) {
	x.TokenUrl = v
}

func (x *OidcConfig) SetClientId(v string) {
	x.ClientId = v
}

func (x *OidcConfig) SetClientSecret(v string) {
	x.ClientSecret = v
}

func (x *OidcConfig) SetIssuer(v string) {
	x.Issuer = v
}

func (x *OidcConfig) SetDefaultScopes(v string) {
	x.DefaultScopes = &v
}

func (x *OidcConfig) SetUserInfoUrl(v string) {
	x.UserInfoUrl = &v
}

func (x *OidcConfig) SetJwksUrl(v string) {
	x.JwksUrl = &v
}

func (x *OidcConfig) SetValidateSignature(v bool) {
	x.ValidateSignature = &v
}

func (x *OidcConfig) SetLogoutUrl(v string) {
	x.LogoutUrl = &v
}

func (x *OidcConfig) HasDefaultScopes() bool {
	if x == nil {
		return false
	}
	return x.DefaultScopes != nil
}

func (x *OidcConfig) HasUserInfoUrl() bool {
	if x == nil {
		return false
	}
	return x.UserInfoUrl != nil
}

func (x *OidcConfig) HasJwksUrl() bool {
	if x == nil {
		return false
	}
	return x.JwksUrl != nil
}

func (x *OidcConfig) HasValidateSignature() bool {
	if x == nil {
		return false
	}
	return x.ValidateSignature != nil
}

func (x *OidcConfig) HasLogoutUrl() bool {
	if x == nil {
		return false
	}
	return x.LogoutUrl != nil
}

func (x *OidcConfig) ClearDefaultScopes() {
	x.DefaultScopes = nil
}

func (x *OidcConfig) ClearUserInfoUrl() {
	x.UserInfoUrl = nil
}

func (x *OidcConfig) ClearJwksUrl() {
	x.JwksUrl = nil
}

func (x *OidcConfig) ClearValidateSignature() {
	x.ValidateSignature = nil
}

func (x *OidcConfig) ClearLogoutUrl() {
	x.LogoutUrl = nil
}

type OidcConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Authorization endpoint URL where users are redirected to authenticate.
	// Example: "https://accounts.google.com/o/oauth2/v2/auth"
	AuthorizationUrl string
	// Token endpoint URL used to exchange authorization codes for access tokens.
	// Example: "https://oauth2.googleapis.com/token"
	TokenUrl string
	// Client identifier issued by the OIDC provider.
	// This is a public identifier for the application.
	ClientId string
	// Client secret for authenticating with the OIDC provider.
	// This field is write-only and will never be returned in API responses.
	ClientSecret string
	// Issuer URL that identifies the OIDC provider.
	// Used for validating ID tokens. Must match the 'iss' claim in tokens.
	// Example: "https://accounts.google.com"
	Issuer string
	// Space-separated list of OAuth scopes to request.
	// Common scopes: "openid profile email"
	// Default: "openid profile email"
	DefaultScopes *string
	// UserInfo endpoint URL for retrieving user profile information.
	// If not specified, user info will be extracted from the ID token.
	// Example: "https://openidconnect.googleapis.com/v1/userinfo"
	UserInfoUrl *string
	// JSON Web Key Set (JWKS) URL for obtaining public keys to verify ID token signatures.
	// If not specified, the provider's discovery endpoint will be used.
	// Example: "https://www.googleapis.com/oauth2/v3/certs"
	JwksUrl *string
	// Whether to validate ID token signatures using JWKS.
	// Default: true
	ValidateSignature *bool
	// Logout URL where users are redirected after logging out.
	// Example: "https://accounts.google.com/logout"
	LogoutUrl *string
}

func (b0 OidcConfig_builder) Build() *OidcConfig {
	m0 := &OidcConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.AuthorizationUrl = b.AuthorizationUrl
	x.TokenUrl = b.TokenUrl
	x.ClientId = b.ClientId
	x.ClientSecret = b.ClientSecret
	x.Issuer = b.Issuer
	x.DefaultScopes = b.DefaultScopes
	x.UserInfoUrl = b.UserInfoUrl
	x.JwksUrl = b.JwksUrl
	x.ValidateSignature = b.ValidateSignature
	x.LogoutUrl = b.LogoutUrl
	return m0
}

// IdentityProviderStatus represents the operational status of an identity provider.
type IdentityProviderStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Phase represents the current phase of the identity provider.
	Phase IdentityProviderPhase `protobuf:"varint,1,opt,name=phase,proto3,enum=osac.public.v1.IdentityProviderPhase" json:"phase,omitempty"`
	// Message provides additional context about the current status.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// This is used by the system to track when the spec.health_check_trigger has changed
	// and to acknowledge that the health check process has started.
	// The system will update it to match spec.health_check_trigger when the check begins.
	// Users can compare this to spec.health_check_trigger to see if their check request has been acknowledged.
	HealthCheckTrigger *string `protobuf:"bytes,3,opt,name=health_check_trigger,json=healthCheckTrigger,proto3,oneof" json:"health_check_trigger,omitempty"`
	// Health check results from the last health check that completed.
	// This is populated after a health check triggered by spec.health_check_trigger completes.
	Health        *IdentityProviderHealth `protobuf:"bytes,4,opt,name=health,proto3,oneof" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProviderStatus) Reset() {
	*x = IdentityProviderStatus{}
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderStatus) ProtoMessage() {}

func (x *IdentityProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderStatus) GetPhase() IdentityProviderPhase {
	if x != nil {
		return x.Phase
	}
	return IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNSPECIFIED
}

func (x *IdentityProviderStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IdentityProviderStatus) GetHealthCheckTrigger() string {
	if x != nil && x.HealthCheckTrigger != nil {
		return *x.HealthCheckTrigger
	}
	return ""
}

func (x *IdentityProviderStatus) GetHealth() *IdentityProviderHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *IdentityProviderStatus) SetPhase(v IdentityProviderPhase) {
	x.Phase = v
}

func (x *IdentityProviderStatus) SetMessage(v string) {
	x.Message = v
}

func (x *IdentityProviderStatus) SetHealthCheckTrigger(v string) {
	x.HealthCheckTrigger = &v
}

func (x *IdentityProviderStatus) SetHealth(v *IdentityProviderHealth) {
	x.Health = v
}

func (x *IdentityProviderStatus) HasHealthCheckTrigger() bool {
	if x == nil {
		return false
	}
	return x.HealthCheckTrigger != nil
}

func (x *IdentityProviderStatus) HasHealth() bool {
	if x == nil {
		return false
	}
	return x.Health != nil
}

func (x *IdentityProviderStatus) ClearHealthCheckTrigger() {
	x.HealthCheckTrigger = nil
}

func (x *IdentityProviderStatus) ClearHealth() {
	x.Health = nil
}

type IdentityProviderStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Phase represents the current phase of the identity provider.
	Phase IdentityProviderPhase
	// Message provides additional context about the current status.
	Message string
	// This is used by the system to track when the spec.health_check_trigger has changed
	// and to acknowledge that the health check process has started.
	// The system will update it to match spec.health_check_trigger when the check begins.
	// Users can compare this to spec.health_check_trigger to see if their check request has been acknowledged.
	HealthCheckTrigger *string
	// Health check results from the last health check that completed.
	// This is populated after a health check triggered by spec.health_check_trigger completes.
	Health *IdentityProviderHealth
}

func (b0 IdentityProviderStatus_builder) Build() *IdentityProviderStatus {
	m0 := &IdentityProviderStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Phase = b.Phase
	x.Message = b.Message
	x.HealthCheckTrigger = b.HealthCheckTrigger
	x.Health = b.Health
	return m0
}

// IdentityProviderHealth represents the health status of an identity provider.
type IdentityProviderHealth struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Status indicates the overall health status.
	Status IdentityProviderHealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=osac.public.v1.IdentityProviderHealthStatus" json:"status,omitempty"`
	// Message provides details about the health status.
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// LastChecked is when the health was last checked.
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProviderHealth) Reset() {
	*x = IdentityProviderHealth{}
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderHealth) ProtoMessage() {}

func (x *IdentityProviderHealth) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_identity_provider_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderHealth) GetStatus() IdentityProviderHealthStatus {
	if x != nil {
		return x.Status
	}
	return IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED
}

func (x *IdentityProviderHealth) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *IdentityProviderHealth) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

func (x *IdentityProviderHealth) SetStatus(v IdentityProviderHealthStatus) {
	x.Status = v
}

func (x *IdentityProviderHealth) SetMessage(v string) {
	x.Message = &v
}

func (x *IdentityProviderHealth) SetLastChecked(v *timestamppb.Timestamp) {
	x.LastChecked = v
}

func (x *IdentityProviderHealth) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *IdentityProviderHealth) HasLastChecked() bool {
	if x == nil {
		return false
	}
	return x.LastChecked != nil
}

func (x *IdentityProviderHealth) ClearMessage() {
	x.Message = nil
}

func (x *IdentityProviderHealth) ClearLastChecked() {
	x.LastChecked = nil
}

type IdentityProviderHealth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status indicates the overall health status.
	Status IdentityProviderHealthStatus
	// Message provides details about the health status.
	Message *string
	// LastChecked is when the health was last checked.
	LastChecked *timestamppb.Timestamp
}

func (b0 IdentityProviderHealth_builder) Build() *IdentityProviderHealth {
	m0 := &IdentityProviderHealth{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	x.Message = b.Message
	x.LastChecked = b.LastChecked
	return m0
}

var File_osac_public_v1_identity_provider_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_identity_provider_type_proto_rawDesc = string([]byte{
	0x0a, 0x2b, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x89, 0x02, 0x0a, 0x14, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x69, 0x64, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x12, 0x35, 0x0a, 0x14, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x12, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x22, 0xd5, 0x03, 0x0a, 0x0a, 0x4f, 0x69, 0x64, 0x63, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x27, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x6a,
	0x77, 0x6b, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x07, 0x6a, 0x77, 0x6b, 0x73, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x12, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x22, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x55, 0x72, 0x6c,
	0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6a, 0x77, 0x6b,
	0x73, 0x5f, 0x75, 0x72, 0x6c, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x22, 0x8f, 0x02, 0x0a, 0x16,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68,
	0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a,
	0x14, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x74, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x12, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x43, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48, 0x01, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0xc8, 0x01,
	0x0a, 0x16, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xab, 0x01, 0x0a, 0x15, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50,
	0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x49,
	0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52,
	0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x21,
	0x0a, 0x1d, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x44, 0x45, 0x52, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x23, 0x0a, 0x1f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52,
	0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x2a, 0xd8, 0x01, 0x0a, 0x1c, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x2b, 0x49, 0x44, 0x45, 0x4e, 0x54,
	0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41,
	0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x2b, 0x0a, 0x27, 0x49, 0x44, 0x45, 0x4e,
	0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45,
	0x41, 0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x48, 0x45, 0x41, 0x4c,
	0x54, 0x48, 0x59, 0x10, 0x01, 0x12, 0x2d, 0x0a, 0x29, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54,
	0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54,
	0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x48, 0x45, 0x41, 0x4c, 0x54,
	0x48, 0x59, 0x10, 0x02, 0x12, 0x2b, 0x0a, 0x27, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59,
	0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x03, 0x42, 0xdd, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x19, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e,
	0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_identity_provider_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osac_public_v1_identity_provider_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_osac_public_v1_identity_provider_type_proto_goTypes = []any{
	(IdentityProviderPhase)(0),        // 0: osac.public.v1.IdentityProviderPhase
	(IdentityProviderHealthStatus)(0), // 1: osac.public.v1.IdentityProviderHealthStatus
	(*IdentityProvider)(nil),          // 2: osac.public.v1.IdentityProvider
	(*IdentityProviderSpec)(nil),      // 3: osac.public.v1.IdentityProviderSpec
	(*OidcConfig)(nil),                // 4: osac.public.v1.OidcConfig
	(*IdentityProviderStatus)(nil),    // 5: osac.public.v1.IdentityProviderStatus
	(*IdentityProviderHealth)(nil),    // 6: osac.public.v1.IdentityProviderHealth
	(*Metadata)(nil),                  // 7: osac.public.v1.Metadata
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_osac_public_v1_identity_provider_type_proto_depIdxs = []int32{
	7, // 0: osac.public.v1.IdentityProvider.metadata:type_name -> osac.public.v1.Metadata
	3, // 1: osac.public.v1.IdentityProvider.spec:type_name -> osac.public.v1.IdentityProviderSpec
	5, // 2: osac.public.v1.IdentityProvider.status:type_name -> osac.public.v1.IdentityProviderStatus
	4, // 3: osac.public.v1.IdentityProviderSpec.oidc:type_name -> osac.public.v1.OidcConfig
	0, // 4: osac.public.v1.IdentityProviderStatus.phase:type_name -> osac.public.v1.IdentityProviderPhase
	6, // 5: osac.public.v1.IdentityProviderStatus.health:type_name -> osac.public.v1.IdentityProviderHealth
	1, // 6: osac.public.v1.IdentityProviderHealth.status:type_name -> osac.public.v1.IdentityProviderHealthStatus
	8, // 7: osac.public.v1.IdentityProviderHealth.last_checked:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_osac_public_v1_identity_provider_type_proto_init() }
func file_osac_public_v1_identity_provider_type_proto_init() {
	if File_osac_public_v1_identity_provider_type_proto != nil {
		return
	}
	file_osac_public_v1_metadata_type_proto_init()
	file_osac_public_v1_identity_provider_type_proto_msgTypes[1].OneofWrappers = []any{
		(*IdentityProviderSpec_Oidc)(nil),
	}
	file_osac_public_v1_identity_provider_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_osac_public_v1_identity_provider_type_proto_msgTypes[3].OneofWrappers = []any{}
	file_osac_public_v1_identity_provider_type_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_identity_provider_type_proto_rawDesc), len(file_osac_public_v1_identity_provider_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_identity_provider_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_identity_provider_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_identity_provider_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_identity_provider_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_identity_provider_type_proto = out.File
	file_osac_public_v1_identity_provider_type_proto_goTypes = nil
	file_osac_public_v1_identity_provider_type_proto_depIdxs = nil
}
